In [9]:
%load_ext autoreload
%autoreload 2

import sys 
sys.path.append("...")

In [93]:
import importlib 
from utils import utils
#from utils.discagens.expert import data_processing
#from utils.pagamentos import metricas_acumuladas, data_processing
from utils.digital_channels import data_processing, metricas_acumuladas
from Ouze.src import config
from utils import utils

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
# importlib.reload(utils)
# importlib.reload(data_wrangling_pagamentos)
# importlib.reload(data_wrangling_acordos)
importlib.reload(data_processing)
importlib.reload(metricas_acumuladas)
importlib.reload(utils)
importlib.reload(config)

In [12]:
import sys
import importlib

# 1. Removemos a referência do módulo da memória
if 'utils.discagens.expert.data_processing' in sys.modules:
    del sys.modules['utils.discagens.expert.data_processing']

# 2. Agora importamos novamente (ele será obrigado a ler do arquivo salvo)
import utils.discagens.expert.data_processing as data_processing

# 3. Teste se a função agora existe lá dentro
if hasattr(data_processing, 'aplicar_transformacoes_discagens'):
    print("Sucesso! A função foi encontrada.")
    # Se quiser trazer para o escopo global:
    from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens
else:
    print("Erro: A função ainda não foi detectada no arquivo. Verifique se salvou o arquivo .py")

Sucesso! A função foi encontrada.

In [73]:
import importlib
import Ouze.src.config as config

importlib.reload(config)

GRUPO_PRINCIPAL_MAP = config.GRUPO_PRINCIPAL_MAP
TRANSFORMACOES_DISCAGENS = config.TRANSFORMACOES_DISCAGENS
DIMENSOES_PAGAMENTOS = config.DIMENSOES_PAGAMENTOS
OUZE_PATHS = config.OUZE_PATHS
CAMINHO_BASE_OUZE = config.CAMINHO_BASE_OUZE

In [ ]:
import sys
# Remover módulos em cache
for mod_name in list(sys.modules.keys()):
    if 'Getnet' in mod_name or 'pagamentos' in mod_name:
        del sys.modules[mod_name]

# Agora importar novamente (vai carregar os arquivos atualizados)
from Getnet.src.consolidacao.pipelines import executar_pipeline_funil_completo

In [3]:
# sobe para Projects 
from Ouze.src.data_loader import load_data_ouze

dados = load_data_ouze('2025-12-01', '2025-12-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\notebooks\..\utils\data_loader.py:251: SyntaxWarning: invalid escape sequence '\P'
  """
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\notebooks\..\utils\data_loader.py:290: SyntaxWarning: invalid escape sequence '\P'
  """

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2025-12-01 até 2025-12-31...

Discagens Expert: 1.540.513 registros
Mailing Histórico: 1.184.839 registros
Tabulação de Acionamentos: 7.623 registros
Tabulação Acionamentos: 45 registros
Calendário: 22 registros
Pagamentos: 598 registros
Acordos: 938 registros
SMS: 19.408 registros
RCS: 19.408 registros
Email: 93.402 registros
Telefones: 231.854 registros
Blacklist Expert: 1.434.857 registros
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [95]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_acumulado_canais_digitais.to_csv('df_acumulado_canais_digitais.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_acumulado_canais_digitais.csv')  # abre com o programa padrão

In [2]:
# sobe para Projects 
from Ouze.src.data_loader import load_data_ouze

dados = load_data_ouze('2026-01-01', '2026-01-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:521: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/12] ✓ Discagens Expert: 1.517.543 registros (4m 48s)
[2/12] ✓ Mailing Histórico: 1.406.663 registros (2m 15s)
[3/12] ✓ Tabulação de Acionamentos: 6.659 registros (2s)
[4/12] ✓ Tabulação Acionamentos: 45 registros (0s)
[5/12] ✓ Calendário: 21 registros (0s)
[6/12] ✓ Pagamentos: 488 registros (2s)
[7/12] ✓ Acordos: 751 registros (0s)
[8/12] ✓ SMS: 12.300 registros (7s)
[9/12] ✓ RCS: 12.300 registros (5s)
[10/12] ✓ Email: 66.563 registros (11s)
[11/12] ✓ Telefones: 245.721 registros (41s)
[12/12] ✓ Blacklist Expert: 1.434.857 registros (14s)

✅ Carregamento concluído em 8m 30s
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [3]:
# Desempacotar os VALORES do dicionário
(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados.values()

In [ ]:
from utils.discagens.expert.data_processing import criar_df_tabulacoes_robo

df_tabulacao = criar_df_tabulacoes_robo()
df_tabulacao

   COD_TABULACAO  ACIONAMENTOS  CPC  CPCA  PROMESSA
0              1             1    0     0         0
1             10             1    1     1         1
2            101             1    0     0         0
3            103             1    0     0         0
4            113             1    0     0         0
5            114             1    0     0         0
6            115             1    0     0         0
7             12             1    0     0         0
8            120             1    1     1         0
9             13             1    1     1         1
10           136             1    0     0         0
11            14             1    0     0         0
12            15             1    1     1         1
13           152             1    1     1         0
14           159             1    1     1         0
15            16             1    1     1         0
16           160             1    1     1         1
17           161             1    1     1         0
18            19             1    1     1         0
19             2             1    0     0         0
20            20             1    1     1         1
21            21             1    1     1         1
22            23             1    1     1         1
23            24             1    1     1         1
24            25             1    1     1         1
25            27             1    1     0         0
26            28             1    1     1         0
27            30             1    1     0         0
28            31             1    1     1         0
29            32             1    1     1         0
30            36             1    1     0         0
31            37             1    1     1         0
32            38             1    1     1         0
33            39             1    1     0         0
34             4             1    1     1         1
35            42             1    1     1         0
36            43             1    1     1         1
37            45             1    1     1         1
38            46             1    1     1         1
39            47             1    1     0         0
40            48             1    1     1         0
41             5             1    0     0         0
42            50             1    0     0         0
43            51             1    1     1         0
44            52             1    0     0         0
45             6             1    1     1         1
46             7             1    1     1         0
47             8             1    0     0         0
48            83             1    0     0         0
49            84             1    0     0         0
50            85             1    0     0         0
51            86             1    1     0         0
52            87             1    1     0         0
53            88             1    0     0         0
54            89             1    0     0         0
55             9             1    0     0         0
56            99             1    0     0         0

In [4]:
from utils.mailing.data_processing import adicionar_faixa_atraso
from utils.mailing.metricas_acumuladas import gerar_acumulado_maling_hist_fxAtraso, gerar_acumulado_maling_hist_unique
from Ouze.src.config import FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS

df_mailing_hist_processing = adicionar_faixa_atraso(df_mailing_hist, FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS)
#df_mailing_hist_processing_acumulado = gerar_acumulado_maling_hist_unique(df_mailing_hist_processing, df_dw_calendario)
df_mailing_hist_processing

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO
0,2026-01-01,0001083530,4987283239,870,253,1,192.17,360 acima
1,2026-01-01,0002022663,11835228941,205,253,1,609.92,181-210
2,2026-01-01,0002269564,70342125206,870,253,1,400.47,360 acima
3,2026-01-01,0002932273,11340283930,144,253,1,483.17,121-150
4,2026-01-01,0003163865,5702519159,103,253,1,254.18,091-120
...,...,...,...,...,...,...,...,...
1406658,2026-01-29,0000050905,11692354841,578,253,1,2.77,360 acima
1406659,2026-01-29,0002559842,1169339255,320,253,1,840.23,301-330
1406660,2026-01-29,0001725935,11693727404,1465,253,1,684.36,360 acima
1406661,2026-01-29,0002182732,1169402208,598,253,1,54.00,360 acima
1406662,2026-01-29,0002642762,1169504396,384,253,1,2374.74,360 acima

In [5]:
from utils.acionamentos.data_processing import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos
from utils.acionamentos.metricas_acumuladas import acionamentos_fxAtraso_origem_humano, acionamentos_unique_humano, acionamentos_esforco_humano


df_mailing_hist_processing = adicionar_faixa_atraso(df_mailing_hist, FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS)
df_tabulacao_aciona_processing = tratar_acionamentos_tabulacao(df_tabulacao_aciona)
df_tab_acionamentos_processing = confere_tabulacao_acionamentos(df_tab_acionamentos, df_tabulacao_aciona_processing)
df_limpo, df_sem_fx_atraso, df_sem_descricao, df_sem_origem = enriquecer_acionamentos(df_tab_acionamentos_processing, df_mailing_hist_processing, df_dw_calendario)
df_acionamentos_fxAtraso = acionamentos_fxAtraso_origem_humano(df_limpo, df_dw_calendario)
#df_acionamentos_unique = acionamentos_unique_humano(df_limpo, df_dw_calendario)
#df_acionamentos_esforco = acionamentos_esforco_humano(df_limpo, df_dw_calendario)

df_acionamentos_fxAtraso

,DATA_ACIONA,FX_ATRASO,ORIGEM,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,Preventivo,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
1,2026-01-05,000-030,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
2,2026-01-05,031-060,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
3,2026-01-05,061-090,HUMANO,0,0.0,1.0,3296.58,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
4,2026-01-05,091-120,HUMANO,0,0.0,30.0,46399.17,2.0,556.42,0.0,0.00,0.0,0.00,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2026-01-30,241-270,HUMANO,0,0.0,196.0,296875.52,51.0,99262.21,33.0,47904.89,14.0,14657.02,21,Q1,1,Jan
276,2026-01-30,271-300,HUMANO,0,0.0,194.0,218700.34,34.0,44313.78,20.0,27656.28,3.0,1461.94,21,Q1,1,Jan
277,2026-01-30,301-330,HUMANO,0,0.0,141.0,212986.38,31.0,73221.87,16.0,32098.26,7.0,2349.77,21,Q1,1,Jan
278,2026-01-30,331-360,HUMANO,0,0.0,99.0,144973.07,17.0,42276.39,6.0,13007.41,2.0,1883.93,21,Q1,1,Jan
279,2026-01-30,360 acima,HUMANO,0,0.0,540.0,877856.44,90.0,136000.74,55.0,67287.71,35.0,25374.81,21,Q1,1,Jan

In [14]:
# from utils.discagens.expert.data_processing import adicionar_operacao
# from Ouze.src.config import GRUPO_PRINCIPAL_MAP

# df_discagens_expert_processing = adicionar_operacao(df_discagens_expert, grupo_map=GRUPO_PRINCIPAL_MAP)
# df_discagens_expert_processing
# # Ouze/src/pipeline_ouze.py

from Ouze.src.config import TRANSFORMACOES_DISCAGENS, DIMENSOES_ACUMULADO
from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens, enriquecer_com_mailing_calendario, criar_df_tabulacoes_robo, enriquecer_com_tabulacoes_robo
from utils.discagens.expert.metricas_acumuladas import acionamentos_fxAtraso_dinamico

# Pipeline limpo
# Aplicar transformações
df_discagens_com_fx_atraso, df_discagens_sem_fx_atraso = aplicar_transformacoes_discagens(
    df=df_discagens_expert,
    config=TRANSFORMACOES_DISCAGENS,
    df_mailing=df_mailing_hist_processing,
    df_calendario=df_dw_calendario
)

df_discagens_expert_processing_treaded = acionamentos_fxAtraso_dinamico(
    df_com_fx_atraso=df_discagens_com_fx_atraso,
    df_dw_calendario=df_dw_calendario,
    dimensoes_agrupamento=DIMENSOES_ACUMULADO
)
df_discagens_expert_processing_treaded

,DATA,FX_ATRASO,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,Preventivo,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
1,2026-01-05,000-030,2.0,107.81,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
2,2026-01-05,031-060,1.0,49.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
3,2026-01-05,061-090,26.0,24154.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
4,2026-01-05,091-120,912.0,675427.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2026-01-30,241-270,1428.0,1704085.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
276,2026-01-30,271-300,1279.0,1456884.76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
277,2026-01-30,301-330,1351.0,1633503.83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
278,2026-01-30,331-360,935.0,1088838.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
279,2026-01-30,360 acima,23696.0,27598051.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan

In [15]:
from utils.utils import transformar_funil_formato_long

df_discagens_acumulado = transformar_funil_formato_long(df_discagens_expert_processing_treaded)
df_discagens_acumulado

,DATA,Indicador,qte,FX_ATRASO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN
0,2026-01-05,ACIONAMENTOS,0.0,Preventivo,Jan,2,Q1,1,0.00
1,2026-01-05,CPC,0.0,Preventivo,Jan,2,Q1,1,0.00
2,2026-01-05,CPCA,0.0,Preventivo,Jan,2,Q1,1,0.00
3,2026-01-05,PROMESSA,0.0,Preventivo,Jan,2,Q1,1,0.00
4,2026-01-05,TRABALHADO,0.0,Preventivo,Jan,2,Q1,1,0.00
...,...,...,...,...,...,...,...,...,...
1395,2026-01-30,ACIONAMENTOS,0.0,360 acima,Jan,21,Q1,1,0.00
1396,2026-01-30,CPC,0.0,360 acima,Jan,21,Q1,1,0.00
1397,2026-01-30,CPCA,0.0,360 acima,Jan,21,Q1,1,0.00
1398,2026-01-30,PROMESSA,0.0,360 acima,Jan,21,Q1,1,0.00
1399,2026-01-30,TRABALHADO,23696.0,360 acima,Jan,21,Q1,1,27598051.07

In [28]:
from utils.pagamentos.data_processing import data_pagamentos
from utils.pagamentos.metricas_acumuladas import gerar_acumulado_por_dia_util
from Ouze.src.config import DIMENSOES_PAGAMENTOS

#df_acordos
df_pagamentos_tratado, df_pagamentos_sem_fx_atraso, df_pagamentos_analitico = data_pagamentos(
    df_pagamentos=df_pagamentos, 
    df_acordos=df_acordos, 
    df_mailing_hist=df_mailing_hist_processing, 
    df_dw_calendario=df_dw_calendario,
    dimensoes_segmentacao=DIMENSOES_PAGAMENTOS
)
df_acumulado, df_esforco, df_unique = gerar_acumulado_por_dia_util(
    df_pagamentos_tratado, 
    DIMENSOES_PAGAMENTOS
)
df_acumulado

,DATA_PAGTO,Indicador,qte,FX_ATRASO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR_PARC
4,2026-01-05,Pagamentos,2,091-120,Jan,2.0,Q1,1.0,248.62
18,2026-01-06,Pagamentos,3,091-120,Jan,3.0,Q1,1.0,408.85
32,2026-01-07,Pagamentos,6,091-120,Jan,4.0,Q1,1.0,1636.55
46,2026-01-08,Pagamentos,8,091-120,Jan,5.0,Q1,1.0,2946.91
49,2026-01-08,Pagamentos,1,181-210,Jan,5.0,Q1,1.0,54.87
...,...,...,...,...,...,...,...,...,...
261,2026-01-30,Pagamentos,2,241-270,Jan,21.0,Q1,1.0,413.28
262,2026-01-30,Pagamentos,2,271-300,Jan,21.0,Q1,1.0,369.71
263,2026-01-30,Pagamentos,2,301-330,Jan,21.0,Q1,1.0,165.49
264,2026-01-30,Pagamentos,2,331-360,Jan,21.0,Q1,1.0,281.95
265,2026-01-30,Pagamentos,11,360 acima,Jan,21.0,Q1,1.0,1652.50

In [ ]:
#df_sms
# df_rcs,
# df_email,
# df_telefones,
# df_blacklist_expert
#df_mailing_hist_processing
mask = df_mailing_hist_processing.duplicated(subset=['DATA', 'CPF'], keep=False)

df_duplicados = df_mailing_hist_processing[mask].sort_values(['DATA', 'CPF'])

df_duplicados

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO
43421,2026-01-01,0001934136,10223017990,210,253,1,9.98,181-210
43464,2026-01-01,0000036817,10223017990,1214,253,1,2797.73,360 acima
39752,2026-01-01,0001732659,1309716188,1483,253,1,255.12,360 acima
39757,2026-01-01,0001595851,1309716188,936,253,1,415.11,360 acima
41140,2026-01-01,0001201654,1549845586,1498,253,1,39.14,360 acima
...,...,...,...,...,...,...,...,...
1381433,2026-01-31,0000027840,93386575153,580,253,1,4.67,360 acima
1382308,2026-01-31,0001068843,94024278568,747,253,1,409.75,360 acima
1382309,2026-01-31,0000909157,94024278568,788,253,1,2316.83,360 acima
1387150,2026-01-31,0001256390,99150549200,1528,253,1,1426.91,360 acima
1387201,2026-01-31,0001115858,99150549200,98,253,1,48.32,091-120

In [83]:
df_mailing_hist_processing
#df_dw_calendario
#df_pagamentos_analitico
#df_sms
#df_email
#df_rcs

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO
0,2026-01-01,0001083530,4987283239,870,253,1,192.17,360 acima
1,2026-01-01,0002022663,11835228941,205,253,1,609.92,181-210
2,2026-01-01,0002269564,70342125206,870,253,1,400.47,360 acima
3,2026-01-01,0002932273,11340283930,144,253,1,483.17,121-150
4,2026-01-01,0003163865,5702519159,103,253,1,254.18,091-120
...,...,...,...,...,...,...,...,...
1406658,2026-01-29,0000050905,11692354841,578,253,1,2.77,360 acima
1406659,2026-01-29,0002559842,1169339255,320,253,1,840.23,301-330
1406660,2026-01-29,0001725935,11693727404,1465,253,1,684.36,360 acima
1406661,2026-01-29,0002182732,1169402208,598,253,1,54.00,360 acima
1406662,2026-01-29,0002642762,1169504396,384,253,1,2374.74,360 acima

In [ ]:
from utils.digital_channels.data_processing import data_channels, unpack_results
from Ouze.src.config import OUZE_PATHS

# Exemplo de uso
df_channels_processing = data_channels(
    df_mailing_hist=df_mailing_hist_processing,
    df_dw_calendario=df_dw_calendario,
    df_sms=df_sms,
    df_email=df_email,
    df_rcs=df_rcs,
    output_path=OUZE_PATHS["digital"],  # Path passado aqui!
)

INFO:utils.utils:
============================================================
INFO:utils.utils:Salvando DataFrames do canal: SMS
INFO:utils.utils:Destino: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_sms
INFO:utils.utils:============================================================
INFO:utils.utils:Diretório verificado/criado: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_sms
INFO:utils.utils:✓ Salvo: sms_enr_20260212.csv (11386 linhas)
INFO:utils.utils:✓ Salvo: sms_sf_20260212.csv (914 linhas)
INFO:utils.utils:
============================================================
INFO:utils.utils:Resumo do salvamento em: data_sms
INFO:utils.utils:  ✓ Sucessos: 2/2
INFO:utils.utils:============================================================
INFO:utils.utils:
============================================================
INFO:utils.utils:Salvando DataFrames do canal: EMAIL
INFO:utils.utils:Destino: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_email
INFO:utils.utils:============================================================
INFO:utils.utils:Diretório verificado/criado: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_email
INFO:utils.utils:✓ Salvo: email_enr_20260212.csv (63317 linhas)
INFO:utils.utils:✓ Salvo: email_sf_20260212.csv (3246 linhas)
INFO:utils.utils:
============================================================
INFO:utils.utils:Resumo do salvamento em: data_email
INFO:utils.utils:  ✓ Sucessos: 2/2
INFO:utils.utils:============================================================
INFO:utils.utils:
============================================================
INFO:utils.utils:Salvando DataFrames do canal: RCS
INFO:utils.utils:Destino: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_rcs
INFO:utils.utils:============================================================
INFO:utils.utils:Diretório verificado/criado: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_rcs
INFO:utils.utils:✓ Salvo: rcs_enr_20260212.csv (11386 linhas)
INFO:utils.utils:✓ Salvo: rcs_sf_20260212.csv (914 linhas)
INFO:utils.utils:
============================================================
INFO:utils.utils:Resumo do salvamento em: data_rcs
INFO:utils.utils:  ✓ Sucessos: 2/2
INFO:utils.utils:============================================================
INFO:utils.utils:
============================================================
INFO:utils.utils:RESUMO GERAL - DIGITAL
INFO:utils.utils:  Canais processados: 3
INFO:utils.utils:  Arquivos salvos: 6/6
INFO:utils.utils:============================================================

{'sms': (            DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  0     2026-01-15   5027943997   211-240    253.0         10.0      Q1     1.0
  1     2026-01-15  93216009904   241-270    253.0         10.0      Q1     1.0
  2     2026-01-15  10588183172   331-360    253.0         10.0      Q1     1.0
  3     2026-01-15  88158632149   301-330    253.0         10.0      Q1     1.0
  4     2026-01-15   6169325291   241-270    253.0         10.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  12295 2026-01-28  47773375291   181-210    253.0         19.0      Q1     1.0
  12296 2026-01-28  56748264120   331-360    253.0         19.0      Q1     1.0
  12297 2026-01-28   5738129180   181-210    253.0         19.0      Q1     1.0
  12298 2026-01-28  41025326253   241-270    253.0         19.0      Q1     1.0
  12299 2026-01-28    968179924   181-210    253.0         19.0      Q1     1.0

        mes_abreviado
  0               Jan
  1               Jan
  2               Jan
  3               Jan
  4               Jan
  ...             ...
  12295           Jan
  12296           Jan
  12297           Jan
  12298           Jan
  12299           Jan

  [11386 rows x 8 columns],
              DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  544   2026-01-15   6223954913       NaN      NaN         10.0      Q1     1.0
  2391  2026-01-21   7038261401       NaN      NaN         14.0      Q1     1.0
  2398  2026-01-21   4052422201       NaN      NaN         14.0      Q1     1.0
  2403  2026-01-21   2400739919       NaN      NaN         14.0      Q1     1.0
  2407  2026-01-21    917772326       NaN      NaN         14.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  12239 2026-01-14   3338714130       NaN      NaN          9.0      Q1     1.0
  12241 2026-01-14  15964362800       NaN      NaN          9.0      Q1     1.0
  12258 2026-01-14  62791982272       NaN      NaN          9.0      Q1     1.0
  12273 2026-01-14   1427327106       NaN      NaN          9.0      Q1     1.0
  12286 2026-01-14  98792806287       NaN      NaN          9.0      Q1     1.0

        mes_abreviado
  544             Jan
  2391            Jan
  2398            Jan
  2403            Jan
  2407            Jan
  ...             ...
  12239           Jan
  12241           Jan
  12258           Jan
  12273           Jan
  12286           Jan

  [914 rows x 8 columns]),
 'email': (            DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  0     2026-01-05   1437114156   211-240    253.0            2      Q1       1
  1     2026-01-05  72327561272   331-360    253.0            2      Q1       1
  2     2026-01-05  72327561272   331-360    253.0            2      Q1       1
  3     2026-01-05  70323704115   211-240    253.0            2      Q1       1
  4     2026-01-05  99037653120   241-270    253.0            2      Q1       1
  ...          ...          ...       ...      ...          ...     ...     ...
  66558 2026-01-29  71736956272   091-120    253.0           20      Q1       1
  66559 2026-01-29  71736956272   091-120    253.0           20      Q1       1
  66560 2026-01-29  71736956272   091-120    253.0           20      Q1       1
  66561 2026-01-29   5109788359   151-180    253.0           20      Q1       1
  66562 2026-01-29  66795427234   091-120    253.0           20      Q1       1

        mes_abreviado
  0               Jan
  1               Jan
  2               Jan
  3               Jan
  4               Jan
  ...             ...
  66558           Jan
  66559           Jan
  66560           Jan
  66561           Jan
  66562           Jan

  [63317 rows x 8 columns],
              DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  872   2026-01-05  43538738220       NaN      NaN            2      Q1       1
  873   2026-01-05  43538738220       NaN      NaN            2      Q1       1
  874   2026-01-05  43538738220       NaN      NaN            2      Q1       1
  1092  2026-01-05  58814205272       NaN      NaN            2      Q1       1
  1093  2026-01-05  58814205272       NaN      NaN            2      Q1       1
  ...          ...          ...       ...      ...          ...     ...     ...
  65659 2026-01-21    500603251       NaN      NaN           14      Q1       1
  65740 2026-01-21    445453044       NaN      NaN           14      Q1       1
  65741 2026-01-21    445453044       NaN      NaN           14      Q1       1
  65742 2026-01-21    445453044       NaN      NaN           14      Q1       1
  66526 2026-01-29  27422305215       NaN      NaN           20      Q1       1

        mes_abreviado
  872             Jan
  873             Jan
  874             Jan
  1092            Jan
  1093            Jan
  ...             ...
  65659           Jan
  65740           Jan
  65741           Jan
  65742           Jan
  66526           Jan

  [3246 rows x 8 columns]),
 'rcs': (            DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  0     2026-01-05  78541590925   091-120    253.0          2.0      Q1     1.0
  1     2026-01-05  43881963987   151-180    253.0          2.0      Q1     1.0
  2     2026-01-05  72742348115   091-120    253.0          2.0      Q1     1.0
  3     2026-01-05   1525997971   151-180    253.0          2.0      Q1     1.0
  5     2026-01-05    241485126   091-120    253.0          2.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  12295 2026-01-28  47773375291   181-210    253.0         19.0      Q1     1.0
  12296 2026-01-28  56748264120   331-360    253.0         19.0      Q1     1.0
  12297 2026-01-28   5738129180   181-210    253.0         19.0      Q1     1.0
  12298 2026-01-28  41025326253   241-270    253.0         19.0      Q1     1.0
  12299 2026-01-28    968179924   181-210    253.0         19.0      Q1     1.0

        mes_abreviado
  0               Jan
  1               Jan
  2               Jan
  3               Jan
  5               Jan
  ...             ...
  12295           Jan
  12296           Jan
  12297           Jan
  12298           Jan
  12299           Jan

  [11386 rows x 8 columns],
              DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  4     2026-01-05   1675714940       NaN      NaN          2.0      Q1     1.0
  14    2026-01-05  42151937100       NaN      NaN          2.0      Q1     1.0
  48    2026-01-05  15115704072       NaN      NaN          2.0      Q1     1.0
  73    2026-01-05  54847001591       NaN      NaN          2.0      Q1     1.0
  104   2026-01-05  28518462215       NaN      NaN          2.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  10955 2026-01-22  45743525900       NaN      NaN         15.0      Q1     1.0
  11900 2026-01-28  38466198172       NaN      NaN         19.0      Q1     1.0
  11904 2026-01-28  25036521315       NaN      NaN         19.0      Q1     1.0
  11936 2026-01-28   4573681280       NaN      NaN         19.0      Q1     1.0
  12004 2026-01-28   3486385232       NaN      NaN         19.0      Q1     1.0

        mes_abreviado
  4               Jan
  14              Jan
  48              Jan
  73              Jan
  104             Jan
  ...             ...
  10955           Jan
  11900           Jan
  11904           Jan
  11936           Jan
  12004           Jan

  [914 rows x 8 columns]),
 'saved_files': {'sms': {'sms_enr': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_sms\\sms_enr_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 11386},
   'sms_sf': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_sms\\sms_sf_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 914}},
  'email': {'email_enr': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_email\\email_enr_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 63317},
   'email_sf': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_email\\email_sf_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 3246}},
  'rcs': {'rcs_enr': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_rcs\\rcs_enr_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 11386},
   'rcs_sf': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_rcs\\rcs_sf_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 914}}}}

In [85]:
from utils.digital_channels.data_processing import data_channels, unpack_results
(
    sms_enr, sms_sf, 
    email_enr, email_sf, 
    rcs_enr, rcs_sf
) = unpack_results(df_channels_processing)
email_enr

,DATA,CPF,FX_ATRASO,COD_CLI,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,1437114156,211-240,253.0,2,Q1,1,Jan
1,2026-01-05,72327561272,331-360,253.0,2,Q1,1,Jan
2,2026-01-05,72327561272,331-360,253.0,2,Q1,1,Jan
3,2026-01-05,70323704115,211-240,253.0,2,Q1,1,Jan
4,2026-01-05,99037653120,241-270,253.0,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...
66558,2026-01-29,71736956272,091-120,253.0,20,Q1,1,Jan
66559,2026-01-29,71736956272,091-120,253.0,20,Q1,1,Jan
66560,2026-01-29,71736956272,091-120,253.0,20,Q1,1,Jan
66561,2026-01-29,5109788359,151-180,253.0,20,Q1,1,Jan
66562,2026-01-29,66795427234,091-120,253.0,20,Q1,1,Jan

In [94]:
from utils.digital_channels.metricas_acumuladas import acumulado_unique, acumulado_por_faixa_atraso, acumulado_esforco

df_acumulado_canais_digitais = acumulado_por_faixa_atraso(
    df_dw_calendario=df_dw_calendario,
    df_sms=sms_enr,
    df_email=email_enr,
    df_rcs=rcs_enr
)
df_acumulado_canais_digitais

,DATA,CANAL,FX_ATRASO,QTD_CPF,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,SMS,Preventivo,0,2,Q1,1,Jan
1,2026-01-05,SMS,000-030,0,2,Q1,1,Jan
2,2026-01-05,SMS,031-060,0,2,Q1,1,Jan
3,2026-01-05,SMS,061-090,0,2,Q1,1,Jan
4,2026-01-05,SMS,091-120,156,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...
765,2026-01-28,RCS,241-270,280,19,Q1,1,Jan
766,2026-01-28,RCS,271-300,173,19,Q1,1,Jan
767,2026-01-28,RCS,301-330,125,19,Q1,1,Jan
768,2026-01-28,RCS,331-360,139,19,Q1,1,Jan
769,2026-01-28,RCS,360 acima,1804,19,Q1,1,Jan