In [16]:
%load_ext autoreload
%autoreload 2

import sys 
sys.path.append("..")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [40]:
import importlib 
#from utils.mailing import data_processing
from utils.discagens.expert import data_processing

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
# importlib.reload(utils)
# importlib.reload(data_wrangling_pagamentos)
# importlib.reload(data_wrangling_acordos)
#importlib.reload(data_processing)
#importlib.reload(metricas_acumuladas)
importlib.reload(data_processing)
#importlib.reload(data_loader)

In [41]:
import importlib
import Ouze.src.config as config

importlib.reload(config)

GRUPO_PRINCIPAL_MAP = config.GRUPO_PRINCIPAL_MAP

In [ ]:
import sys
# Remover módulos em cache
for mod_name in list(sys.modules.keys()):
    if 'Getnet' in mod_name or 'pagamentos' in mod_name:
        del sys.modules[mod_name]

# Agora importar novamente (vai carregar os arquivos atualizados)
from Getnet.src.consolidacao.pipelines import executar_pipeline_funil_completo

In [3]:
# sobe para Projects 
from Ouze.src.data_loader import load_data_ouze

dados = load_data_ouze('2025-12-01', '2025-12-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\notebooks\..\utils\data_loader.py:251: SyntaxWarning: invalid escape sequence '\P'
  """
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\notebooks\..\utils\data_loader.py:290: SyntaxWarning: invalid escape sequence '\P'
  """

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2025-12-01 até 2025-12-31...

Discagens Expert: 1.540.513 registros
Mailing Histórico: 1.184.839 registros
Tabulação de Acionamentos: 7.623 registros
Tabulação Acionamentos: 45 registros
Calendário: 22 registros
Pagamentos: 598 registros
Acordos: 938 registros
SMS: 19.408 registros
RCS: 19.408 registros
Email: 93.402 registros
Telefones: 231.854 registros
Blacklist Expert: 1.434.857 registros
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [36]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_acionamentos_fxAtraso.to_csv('df_acionamentos_fxAtraso.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_acionamentos_fxAtraso.csv')  # abre com o programa padrão

In [2]:
# sobe para Projects 
from Ouze.src.data_loader import load_data_ouze

dados = load_data_ouze('2026-01-01', '2026-01-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:521: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/12] ✓ Discagens Expert: 1.517.543 registros (5m 28s)
[2/12] ✓ Mailing Histórico: 1.406.663 registros (1m 40s)
[3/12] ✓ Tabulação de Acionamentos: 6.659 registros (5s)
[4/12] ✓ Tabulação Acionamentos: 45 registros (0s)
[5/12] ✓ Calendário: 21 registros (0s)
[6/12] ✓ Pagamentos: 488 registros (6s)
[7/12] ✓ Acordos: 751 registros (2s)
[8/12] ✓ SMS: 12.300 registros (4s)
[9/12] ✓ RCS: 12.300 registros (1s)
[10/12] ✓ Email: 66.563 registros (2s)
[11/12] ✓ Telefones: 242.524 registros (43s)
[12/12] ✓ Blacklist Expert: 1.434.857 registros (2m 59s)

✅ Carregamento concluído em 11m 13s
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [ ]:
# Desempacotar os VALORES do dicionário
(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados.values()

In [1]:
df_discagens_expert

NameError: name 'df_discagens_expert' is not defined

In [23]:
from utils.mailing.data_processing import adicionar_faixa_atraso
from utils.mailing.metricas_acumuladas import gerar_acumulado_maling_hist_fxAtraso, gerar_acumulado_maling_hist_unique
from Ouze.src.config import FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS

df_mailing_hist_processing = adicionar_faixa_atraso(df_mailing_hist, FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS)
df_mailing_hist_processing = gerar_acumulado_maling_hist_unique(df_mailing_hist_processing, df_dw_calendario)
df_mailing_hist_processing

,DATA,Indicador,qte,FX_ATRASO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR
0,2026-01-02,Contratos,43698,Unique,Jan,1,Q1,1,40739840.34
1,2026-01-02,Carteira (CPFs),43673,Unique,Jan,1,Q1,1,40711310.40
2,2026-01-05,Contratos,43698,Unique,Jan,2,Q1,1,40739840.34
3,2026-01-05,Carteira (CPFs),43673,Unique,Jan,2,Q1,1,40720847.46
4,2026-01-06,Contratos,46180,Unique,Jan,3,Q1,1,43079699.43
5,2026-01-06,Carteira (CPFs),46154,Unique,Jan,3,Q1,1,43054879.77
6,2026-01-07,Contratos,49041,Unique,Jan,4,Q1,1,46158721.19
7,2026-01-07,Carteira (CPFs),49010,Unique,Jan,4,Q1,1,46086342.31
8,2026-01-08,Contratos,50604,Unique,Jan,5,Q1,1,47840816.43
9,2026-01-08,Carteira (CPFs),50573,Unique,Jan,5,Q1,1,47801326.09
10,2026-01-09,Contratos,52256,Unique,Jan,6,Q1,1,49787611.51
11,2026-01-09,Carteira (CPFs),52226,Unique,Jan,6,Q1,1,49734938.71
12,2026-01-12,Contratos,58075,Unique,Jan,7,Q1,1,55657532.31
13,2026-01-12,Carteira (CPFs),58039,Unique,Jan,7,Q1,1,55585720.54
14,2026-01-13,Contratos,58779,Unique,Jan,8,Q1,1,56325100.83
15,2026-01-13,Carteira (CPFs),58742,Unique,Jan,8,Q1,1,56272005.17
16,2026-01-14,Contratos,59144,Unique,Jan,9,Q1,1,56691923.22
17,2026-01-14,Carteira (CPFs),59104,Unique,Jan,9,Q1,1,56629626.10
18,2026-01-15,Contratos,60602,Unique,Jan,10,Q1,1,58258604.07
19,2026-01-15,Carteira (CPFs),60559,Unique,Jan,10,Q1,1,58212050.15
20,2026-01-16,Contratos,61020,Unique,Jan,11,Q1,1,58600815.37
21,2026-01-16,Carteira (CPFs),60977,Unique,Jan,11,Q1,1,58530581.67
22,2026-01-19,Contratos,62452,Unique,Jan,12,Q1,1,60282727.19
23,2026-01-19,Carteira (CPFs),62405,Unique,Jan,12,Q1,1,60212480.18
24,2026-01-20,Contratos,63809,Unique,Jan,13,Q1,1,61721139.95
25,2026-01-20,Carteira (CPFs),63761,Unique,Jan,13,Q1,1,61657011.16
26,2026-01-21,Contratos,63809,Unique,Jan,14,Q1,1,61721139.95
27,2026-01-21,Carteira (CPFs),63761,Unique,Jan,14,Q1,1,61662780.88
28,2026-01-22,Contratos,64397,Unique,Jan,15,Q1,1,62342469.40
29,2026-01-22,Carteira (CPFs),64349,Unique,Jan,15,Q1,1,62274507.66
30,2026-01-23,Contratos,65557,Unique,Jan,16,Q1,1,63863248.24
31,2026-01-23,Carteira (CPFs),65502,Unique,Jan,16,Q1,1,63798965.27
32,2026-01-26,Contratos,68391,Unique,Jan,17,Q1,1,66601011.71
33,2026-01-26,Carteira (CPFs),68338,Unique,Jan,17,Q1,1,66534306.59
34,2026-01-27,Contratos,68997,Unique,Jan,18,Q1,1,67276454.24
35,2026-01-27,Carteira (CPFs),68943,Unique,Jan,18,Q1,1,67204535.10
36,2026-01-28,Contratos,69486,Unique,Jan,19,Q1,1,67953261.39
37,2026-01-28,Carteira (CPFs),69428,Unique,Jan,19,Q1,1,67882247.31
38,2026-01-29,Contratos,69659,Unique,Jan,20,Q1,1,68265452.06
39,2026-01-29,Carteira (CPFs),69601,Unique,Jan,20,Q1,1,68183458.44
40,2026-01-30,Contratos,69840,Unique,Jan,21,Q1,1,68980504.51
41,2026-01-30,Carteira (CPFs),69783,Unique,Jan,21,Q1,1,68910819.79

In [35]:
from utils.acionamentos.data_processing import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos
from utils.acionamentos.metricas_acumuladas import acionamentos_fxAtraso_origem_humano, acionamentos_unique_humano, acionamentos_esforco_humano


df_mailing_hist_processing = adicionar_faixa_atraso(df_mailing_hist, FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS)
df_tabulacao_aciona_processing = tratar_acionamentos_tabulacao(df_tabulacao_aciona)
df_tab_acionamentos_processing = confere_tabulacao_acionamentos(df_tab_acionamentos, df_tabulacao_aciona_processing)
df_limpo, df_sem_fx_atraso, df_sem_descricao, df_sem_origem = enriquecer_acionamentos(df_tab_acionamentos_processing, df_mailing_hist_processing, df_dw_calendario)
df_acionamentos_fxAtraso = acionamentos_fxAtraso_origem_humano(df_limpo, df_dw_calendario)
#df_acionamentos_unique = acionamentos_unique_humano(df_limpo, df_dw_calendario)
#df_acionamentos_esforco = acionamentos_esforco_humano(df_limpo, df_dw_calendario)

df_acionamentos_fxAtraso

,DATA_ACIONA,FX_ATRASO,ORIGEM,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,Preventivo,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
1,2026-01-05,000-030,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
2,2026-01-05,031-060,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
3,2026-01-05,061-090,HUMANO,0,0.0,1.0,3296.58,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
4,2026-01-05,091-120,HUMANO,0,0.0,30.0,46399.17,2.0,556.42,0.0,0.00,0.0,0.00,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2026-01-30,241-270,HUMANO,0,0.0,196.0,296875.52,51.0,99262.21,33.0,47904.89,14.0,14657.02,21,Q1,1,Jan
276,2026-01-30,271-300,HUMANO,0,0.0,194.0,218700.34,34.0,44313.78,20.0,27656.28,3.0,1461.94,21,Q1,1,Jan
277,2026-01-30,301-330,HUMANO,0,0.0,141.0,214755.74,31.0,74991.23,16.0,32098.26,7.0,2349.77,21,Q1,1,Jan
278,2026-01-30,331-360,HUMANO,0,0.0,99.0,144973.07,17.0,42276.39,6.0,13007.41,2.0,1883.93,21,Q1,1,Jan
279,2026-01-30,360 acima,HUMANO,0,0.0,540.0,876013.53,90.0,135342.75,55.0,67287.71,35.0,25374.81,21,Q1,1,Jan

In [42]:
from utils.discagens.expert.data_processing import adicionar_operacao
from Ouze.src.config import GRUPO_PRINCIPAL_MAP

df_discagens_expert_processing = adicionar_operacao(df_discagens_expert, grupo_map=GRUPO_PRINCIPAL_MAP)
df_discagens_expert_processing

,DATA,id,CONTRATO,CPF,ddd,fone,GrupoPrincipal,UltCodSigRecPublica,ResultadoClassificacao,MotivoEncerramentoBilhete,Instante200OKPub,Agente,tempoconversacao_ms,codtabulacao,OPERACAO
0,2026-01-05,21,0002080165,41490177272,93,991959645,4715,200,cxpre,bloqueiodetector,2026-01-05 09:47:04,,0,None,AGV NEGOCIADORA
1,2026-01-05,192,0002072787,64245802200,92,993713303,4715,404,,foneinexistente,1899-12-30 00:00:00,,0,None,AGV NEGOCIADORA
2,2026-01-05,225,0002142198,4469642126,65,36854587,4715,408,,naoatende,1899-12-30 00:00:00,,0,None,AGV NEGOCIADORA
3,2026-01-05,236,0000143191,4356148193,65,36857981,4715,480,,foneforadeservico,1899-12-30 00:00:00,,0,None,AGV NEGOCIADORA
4,2026-01-05,325,0002444108,2005069,56,799914986,4715,404,,foneinexistente,1899-12-30 00:00:00,,0,None,AGV NEGOCIADORA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1517538,2026-01-31,51710275,0002371134,38214300525,71,999020050,4713,408,,naoatende,1899-12-30 00:00:00,,0,None,ATIVO
1517539,2026-01-31,51710276,0002746631,59218673220,69,992997922,4713,200,cxpos,bloqueiodetector,2026-01-31 14:09:17,,0,None,ATIVO
1517540,2026-01-31,51710278,0002870496,56106440204,92,36578384,4713,480,,foneforadeservico,1899-12-30 00:00:00,,0,None,ATIVO
1517541,2026-01-31,51710290,0002379468,66084326234,92,988540078,4713,200,silencio,bloqueiodetector,2026-01-31 14:09:18,,0,None,ATIVO
1517542,2026-01-31,51710298,0001937956,3503614109,65,996894957,4713,408,,naoatende,1899-12-30 00:00:00,,0,None,ATIVO