In [68]:
%load_ext autoreload
%autoreload 2

import sys 
sys.path.append("...")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [72]:
import importlib 
#from utils.mailing import data_processing
#from utils.discagens.expert import data_processing
from utils import utils
#from Ouze.src.config import data_processing

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
# importlib.reload(utils)
# importlib.reload(data_wrangling_pagamentos)
# importlib.reload(data_wrangling_acordos)
#importlib.reload(data_processing)
#importlib.reload(metricas_acumuladas)
importlib.reload(utils)
#importlib.reload(data_loader)

In [67]:
import sys
import importlib

# 1. Removemos a referência do módulo da memória
if 'utils.discagens.expert.data_processing' in sys.modules:
    del sys.modules['utils.discagens.expert.data_processing']

# 2. Agora importamos novamente (ele será obrigado a ler do arquivo salvo)
import utils.discagens.expert.data_processing as data_processing

# 3. Teste se a função agora existe lá dentro
if hasattr(data_processing, 'aplicar_transformacoes_discagens'):
    print("Sucesso! A função foi encontrada.")
    # Se quiser trazer para o escopo global:
    from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens
else:
    print("Erro: A função ainda não foi detectada no arquivo. Verifique se salvou o arquivo .py")

Sucesso! A função foi encontrada.

In [69]:
import importlib
import Ouze.src.config as config

importlib.reload(config)

GRUPO_PRINCIPAL_MAP = config.GRUPO_PRINCIPAL_MAP
TRANSFORMACOES_DISCAGENS = config.TRANSFORMACOES_DISCAGENS

In [ ]:
import sys
# Remover módulos em cache
for mod_name in list(sys.modules.keys()):
    if 'Getnet' in mod_name or 'pagamentos' in mod_name:
        del sys.modules[mod_name]

# Agora importar novamente (vai carregar os arquivos atualizados)
from Getnet.src.consolidacao.pipelines import executar_pipeline_funil_completo

In [3]:
# sobe para Projects 
from Ouze.src.data_loader import load_data_ouze

dados = load_data_ouze('2025-12-01', '2025-12-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\notebooks\..\utils\data_loader.py:251: SyntaxWarning: invalid escape sequence '\P'
  """
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\notebooks\..\utils\data_loader.py:290: SyntaxWarning: invalid escape sequence '\P'
  """

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2025-12-01 até 2025-12-31...

Discagens Expert: 1.540.513 registros
Mailing Histórico: 1.184.839 registros
Tabulação de Acionamentos: 7.623 registros
Tabulação Acionamentos: 45 registros
Calendário: 22 registros
Pagamentos: 598 registros
Acordos: 938 registros
SMS: 19.408 registros
RCS: 19.408 registros
Email: 93.402 registros
Telefones: 231.854 registros
Blacklist Expert: 1.434.857 registros
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [55]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_discagens_expert_processing_treaded.to_csv('df_discagens_expert_processing_treaded.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_discagens_expert_processing_treaded.csv')  # abre com o programa padrão

In [2]:
# sobe para Projects 
from Ouze.src.data_loader import load_data_ouze

dados = load_data_ouze('2026-01-01', '2026-01-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:521: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/12] ✓ Discagens Expert: 1.517.543 registros (5m 28s)
[2/12] ✓ Mailing Histórico: 1.406.663 registros (1m 40s)
[3/12] ✓ Tabulação de Acionamentos: 6.659 registros (5s)
[4/12] ✓ Tabulação Acionamentos: 45 registros (0s)
[5/12] ✓ Calendário: 21 registros (0s)
[6/12] ✓ Pagamentos: 488 registros (6s)
[7/12] ✓ Acordos: 751 registros (2s)
[8/12] ✓ SMS: 12.300 registros (4s)
[9/12] ✓ RCS: 12.300 registros (1s)
[10/12] ✓ Email: 66.563 registros (2s)
[11/12] ✓ Telefones: 242.524 registros (43s)
[12/12] ✓ Blacklist Expert: 1.434.857 registros (2m 59s)

✅ Carregamento concluído em 11m 13s
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [4]:
# Desempacotar os VALORES do dicionário
(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_telefones,
df_blacklist_expert
) = dados.values()

In [58]:
from utils.discagens.expert.data_processing import criar_df_tabulacoes_robo
df_tabulacao = criar_df_tabulacoes_robo()
df_tabulacao

   COD_TABULACAO  ACIONAMENTOS  CPC  CPCA  PROMESSA
0              1             1    0     0         0
1             10             1    1     1         1
2            101             1    0     0         0
3            103             1    0     0         0
4            113             1    0     0         0
5            114             1    0     0         0
6            115             1    0     0         0
7             12             1    0     0         0
8            120             1    1     1         0
9             13             1    1     1         1
10           136             1    0     0         0
11            14             1    0     0         0
12            15             1    1     1         1
13           152             1    1     1         0
14           159             1    1     1         0
15            16             1    1     1         0
16           160             1    1     1         1
17           161             1    1     1         0
18            19             1    1     1         0
19             2             1    0     0         0
20            20             1    1     1         1
21            21             1    1     1         1
22            23             1    1     1         1
23            24             1    1     1         1
24            25             1    1     1         1
25            27             1    1     0         0
26            28             1    1     1         0
27            30             1    1     0         0
28            31             1    1     1         0
29            32             1    1     1         0
30            36             1    1     0         0
31            37             1    1     1         0
32            38             1    1     1         0
33            39             1    1     0         0
34             4             1    1     1         1
35            42             1    1     1         0
36            43             1    1     1         1
37            45             1    1     1         1
38            46             1    1     1         1
39            47             1    1     0         0
40            48             1    1     1         0
41             5             1    0     0         0
42            50             1    0     0         0
43            51             1    1     1         0
44            52             1    0     0         0
45             6             1    1     1         1
46             7             1    1     1         0
47             8             1    0     0         0
48            83             1    0     0         0
49            84             1    0     0         0
50            85             1    0     0         0
51            86             1    1     0         0
52            87             1    1     0         0
53            88             1    0     0         0
54            89             1    0     0         0
55             9             1    0     0         0
56            99             1    0     0         0

In [44]:
from utils.mailing.data_processing import adicionar_faixa_atraso
from utils.mailing.metricas_acumuladas import gerar_acumulado_maling_hist_fxAtraso, gerar_acumulado_maling_hist_unique
from Ouze.src.config import FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS

df_mailing_hist_processing = adicionar_faixa_atraso(df_mailing_hist, FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS)
#df_mailing_hist_processing = gerar_acumulado_maling_hist_unique(df_mailing_hist_processing, df_dw_calendario)
df_mailing_hist_processing

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO
0,2026-01-01,0003189640,97671517100,144,253,1,185.62,121-150
1,2026-01-01,0000583337,53206053153,417,253,1,83.74,360 acima
2,2026-01-01,0002886899,59439025972,341,253,1,55.15,331-360
3,2026-01-01,0000996159,232484082,356,253,1,1193.89,331-360
4,2026-01-01,0000986749,5474835469,1138,253,1,858.80,360 acima
...,...,...,...,...,...,...,...,...
1406658,2026-01-30,0001369261,82436967253,1264,253,1,642.18,360 acima
1406659,2026-01-30,0002933033,11058029304,10,253,1,833.43,000-030
1406660,2026-01-30,0002616173,10379184958,359,253,1,303.06,331-360
1406661,2026-01-30,0002166764,1124612122,868,253,1,502.63,360 acima
1406662,2026-01-30,0001822836,43609314842,1376,253,1,435.65,360 acima

In [35]:
from utils.acionamentos.data_processing import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos
from utils.acionamentos.metricas_acumuladas import acionamentos_fxAtraso_origem_humano, acionamentos_unique_humano, acionamentos_esforco_humano


df_mailing_hist_processing = adicionar_faixa_atraso(df_mailing_hist, FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS)
df_tabulacao_aciona_processing = tratar_acionamentos_tabulacao(df_tabulacao_aciona)
df_tab_acionamentos_processing = confere_tabulacao_acionamentos(df_tab_acionamentos, df_tabulacao_aciona_processing)
df_limpo, df_sem_fx_atraso, df_sem_descricao, df_sem_origem = enriquecer_acionamentos(df_tab_acionamentos_processing, df_mailing_hist_processing, df_dw_calendario)
df_acionamentos_fxAtraso = acionamentos_fxAtraso_origem_humano(df_limpo, df_dw_calendario)
#df_acionamentos_unique = acionamentos_unique_humano(df_limpo, df_dw_calendario)
#df_acionamentos_esforco = acionamentos_esforco_humano(df_limpo, df_dw_calendario)

df_acionamentos_fxAtraso

,DATA_ACIONA,FX_ATRASO,ORIGEM,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,Preventivo,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
1,2026-01-05,000-030,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
2,2026-01-05,031-060,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
3,2026-01-05,061-090,HUMANO,0,0.0,1.0,3296.58,0.0,0.00,0.0,0.00,0.0,0.00,2,Q1,1,Jan
4,2026-01-05,091-120,HUMANO,0,0.0,30.0,46399.17,2.0,556.42,0.0,0.00,0.0,0.00,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2026-01-30,241-270,HUMANO,0,0.0,196.0,296875.52,51.0,99262.21,33.0,47904.89,14.0,14657.02,21,Q1,1,Jan
276,2026-01-30,271-300,HUMANO,0,0.0,194.0,218700.34,34.0,44313.78,20.0,27656.28,3.0,1461.94,21,Q1,1,Jan
277,2026-01-30,301-330,HUMANO,0,0.0,141.0,214755.74,31.0,74991.23,16.0,32098.26,7.0,2349.77,21,Q1,1,Jan
278,2026-01-30,331-360,HUMANO,0,0.0,99.0,144973.07,17.0,42276.39,6.0,13007.41,2.0,1883.93,21,Q1,1,Jan
279,2026-01-30,360 acima,HUMANO,0,0.0,540.0,876013.53,90.0,135342.75,55.0,67287.71,35.0,25374.81,21,Q1,1,Jan

In [71]:
# from utils.discagens.expert.data_processing import adicionar_operacao
# from Ouze.src.config import GRUPO_PRINCIPAL_MAP

# df_discagens_expert_processing = adicionar_operacao(df_discagens_expert, grupo_map=GRUPO_PRINCIPAL_MAP)
# df_discagens_expert_processing
# # Ouze/src/pipeline_ouze.py

from Ouze.src.config import TRANSFORMACOES_DISCAGENS, DIMENSOES_ACUMULADO
from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens, enriquecer_com_mailing_calendario, criar_df_tabulacoes_robo, enriquecer_com_tabulacoes_robo
from utils.discagens.expert.metricas_acumuladas import acionamentos_fxAtraso_dinamico

# Pipeline limpo
# Aplicar transformações
df_discagens_com_fx_atraso, df_discagens_sem_fx_atraso = aplicar_transformacoes_discagens(
    df=df_discagens_expert,
    config=TRANSFORMACOES_DISCAGENS,
    df_mailing=df_mailing_hist_processing,
    df_calendario=df_dw_calendario
)

df_discagens_expert_processing_treaded = acionamentos_fxAtraso_dinamico(
    df_com_fx_atraso=df_discagens_com_fx_atraso,
    df_dw_calendario=df_dw_calendario,
    dimensoes_agrupamento=DIMENSOES_ACUMULADO
)
df_discagens_expert_processing_treaded

,DATA,FX_ATRASO,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,Preventivo,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
1,2026-01-05,000-030,2.0,107.81,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
2,2026-01-05,031-060,1.0,49.86,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
3,2026-01-05,061-090,26.0,24154.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
4,2026-01-05,091-120,912.0,675427.11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,2026-01-30,241-270,1428.0,1704085.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
276,2026-01-30,271-300,1279.0,1456884.76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
277,2026-01-30,301-330,1351.0,1633503.83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
278,2026-01-30,331-360,935.0,1088838.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan
279,2026-01-30,360 acima,23696.0,27598051.07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21,Q1,1,Jan

In [73]:
from utils.utils import transformar_funil_formato_long

df_discagens_acumulado = transformar_funil_formato_long(df_discagens_expert_processing_treaded)
df_discagens_acumulado

,DATA,Indicador,qte,FX_ATRASO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN
0,2026-01-05,ACIONAMENTOS,0.0,Preventivo,Jan,2,Q1,1,0.00
1,2026-01-05,CPC,0.0,Preventivo,Jan,2,Q1,1,0.00
2,2026-01-05,CPCA,0.0,Preventivo,Jan,2,Q1,1,0.00
3,2026-01-05,PROMESSA,0.0,Preventivo,Jan,2,Q1,1,0.00
4,2026-01-05,TRABALHADO,0.0,Preventivo,Jan,2,Q1,1,0.00
...,...,...,...,...,...,...,...,...,...
1395,2026-01-30,ACIONAMENTOS,0.0,360 acima,Jan,21,Q1,1,0.00
1396,2026-01-30,CPC,0.0,360 acima,Jan,21,Q1,1,0.00
1397,2026-01-30,CPCA,0.0,360 acima,Jan,21,Q1,1,0.00
1398,2026-01-30,PROMESSA,0.0,360 acima,Jan,21,Q1,1,0.00
1399,2026-01-30,TRABALHADO,23696.0,360 acima,Jan,21,Q1,1,27598051.07