In [147]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_acionamentos_tabulados.to_csv('df_acionamentos_tabulados.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_acionamentos_tabulados.csv')  # abre com o programa padrão

In [139]:
%load_ext autoreload
%autoreload 2

import sys 
sys.path.append("..")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [140]:
import importlib 
from Getnet.src import data_loader, data_wrangling_mailingHist, utils, data_wrangling_pagamentos, data_wrangling_acordos,data_wrangling_acionamentos
from utils import data_loader, queries
importlib.reload(data_loader)
importlib.reload(queries)
importlib.reload(data_wrangling_mailingHist)
#importlib.reload(queries)
importlib.reload(utils)
importlib.reload(data_wrangling_pagamentos)
importlib.reload(data_wrangling_acordos)
importlib.reload(data_wrangling_acionamentos)

<module 'Getnet.src.data_wrangling_acionamentos' from 'c:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\notebooks\\..\\Getnet\\src\\data_wrangling_acionamentos.py'>

In [104]:
# sobe para Projects 
from Getnet.src.data_loader import load_data_getnet

dados = load_data_getnet('2026-01-01', '2026-01-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
# df_sms,
# df_rcs,
# df_email,
# df_telefones,
) = dados

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

Discagens Expert: 343.327 registros
Mailing Histórico: 2.399.521 registros
Tabulação de Acionamentos: 1.617 registros
Tabulação Acionamentos: 79 registros
Calendário: 21 registros
Pagamentos: 18.657 registros
Acordos: 2.234 registros
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [106]:
# Desempacotar os VALORES do dicionário
(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona, 
df_dw_calendario, 
df_pagamentos, 
df_acordos
) = dados.values()

In [145]:
df_tab_acionamentos

,DATA_ACIONA,HORA,CONTRATO_FIN,CPF_DEV,COD_ACIONA,DESC_ACIONAMENTO,COD_RECUP,NOME_RECUP,LOGIN_RECUP,ULTGRUPO_RECUP,COD_CLI,VALORPRIN_FIN,STATCONT_FIN,DTDEVOL_FIN,DTENTRADA_FIN,CLASSIFICACAO_ACIONAMENTO
0,2026-01-19,12:52:28.973333,30017503ID,13772282000197,5779,OUTROS-CRESOL,17275,ANDREZA LOPES,ANDREZA_RN,CRESOL,228,79.90,1,2023-02-02 16:29:45.740,2022-09-12 12:46:47.690,0
1,2026-01-14,08:55:32.200000,35940473ID,2465638343,8820,ATENDE E DESLIGA - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,228,547.58,0,NaT,2023-09-22 11:09:01.543,1
2,2026-01-08,09:20:49.956666,36251223ID,32590444000110,8914,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,228,716.39,0,NaT,2023-10-04 12:15:14.353,1
3,2026-01-12,09:40:35.740000,30082994ID,40881937000138,8820,ATENDE E DESLIGA - GETNET,19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,228,761.28,0,NaT,2023-12-29 12:03:48.800,1
4,2026-01-06,08:53:44.913333,30064441ID,46391479000135,4611,TEMPO EXCEDIDO (SEM MARCAÇÃO),19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,228,20664.58,0,NaT,2023-12-30 07:08:14.730,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,2026-01-02,13:56:31.460000,55038276ID,3010734816,8820,ATENDE E DESLIGA - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,228,189.80,0,NaT,2026-01-20 07:02:18.213,1
1613,2026-01-12,10:38:12.886666,55609042ID,34172985000235,7021,PROMESSA DE PAGAMENTO - GETNET,19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,228,184.91,0,NaT,2026-01-20 07:02:18.213,1
1614,2026-01-08,08:46:13.493333,55043365ID,4864713812,7021,PROMESSA DE PAGAMENTO - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,228,79.90,0,NaT,2026-01-20 07:02:18.213,1
1615,2026-01-20,11:39:50.773333,55726077ID,5650282862,4611,TEMPO EXCEDIDO (SEM MARCAÇÃO),19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,228,479.40,0,NaT,2026-01-20 07:02:18.213,0
1616,2026-01-20,10:43:39.993333,55726018ID,58525547000190,7028,DESCONHECE O CLIENTE - GETNET,19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,228,579.75,0,NaT,2026-01-20 07:02:18.213,1

In [118]:
from Getnet.src.data_wrangling_mailingHist import tratar_base_mailing_hist
from Getnet.src.data_wrangling_acordos import adicionar_tipo_negociacao

df_mailing_hist_tratado = tratar_base_mailing_hist(df_mailing_hist)
df_acordos_tratado = adicionar_tipo_negociacao(df_acordos)
#df_mailing_hist_tratado 
df_acordos_tratado

,CONTRATO_FIN,CPF_DEV,DATA_ACORDO,VENC_PARCELA,CANC_ACORDO,NACORDO_ACO,VLRACORDO_ACO,VALOR_ACOP,RECUP_ACO,PARCELA_ACOP,COD_STAC,RECUPERADOR,COD_CLI,COD_CAR,ATRASO_FIN,TIPO
0,29480630ID,31957666000166,2026-01-06,2026-01-08,2026-01-15,2,72.50,72.50,11003,1,5,ASC,228,2,194,ROBÔ
1,29481435ID,37046492000166,2026-01-13,2026-01-14,1900-01-01,4,101.44,101.44,11003,1,4,ASC,228,2,6,ROBÔ
2,29495144ID,9284468000120,2026-01-14,2026-01-15,1900-01-01,4,186.13,186.13,11003,1,4,ASC,228,2,5,ROBÔ
3,29517519ID,39304999000106,2026-01-13,2026-01-14,1900-01-01,7,71.67,71.67,11003,1,4,ASC,228,2,6,ROBÔ
4,29985119ID,37748909000132,2026-01-02,2026-01-02,2026-01-09,1,214.96,214.96,19083,1,5,CARLA FERNANDA VULCANIS,228,2,134,HUMANO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2229,55703233ID,63367994000107,2026-01-19,2026-01-20,None,1,36.74,36.74,11003,1,3,ASC,228,2,0,ROBÔ
2230,55703440ID,6862627029705,2026-01-17,2026-01-19,None,1,35.61,35.61,11003,1,3,ASC,228,2,1,ROBÔ
2231,55703594ID,521015766,2026-01-19,2026-01-20,None,1,37.99,37.99,11003,1,9,ASC,228,2,0,ROBÔ
2232,55703770ID,59102158000115,2026-01-20,2026-01-21,None,1,79.89,79.89,11003,1,3,ASC,228,2,-1,ROBÔ
2233,55703787ID,37149210000156,2026-01-19,2026-01-21,None,1,61.94,61.94,11003,1,3,ASC,228,2,-1,ROBÔ

In [97]:
from Getnet.src.data_wrangling_pagamentos import data_pagamentos, gerar_acumulado_por_dia_util

df_pagamento, df_sem_fx_atraso, df_pagamentos_analitico = data_pagamentos(df_pagamentos, df_acordos, df_mailing_hist, df_dw_calendario)
df_pagamentos_funil, df_esforco, df_unique = gerar_acumulado_por_dia_util(df_pagamento)
df_pagamentos_funil

,DATA_PAGTO,Indicador,qte,FX_ATRASO,TIPO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR_PARC
1,2026-01-05,Pagamentos,1,0-30,HUMANO,Jan,2,Q1,1,112.27
12,2026-01-06,Pagamentos,6,0-30,HUMANO,Jan,3,Q1,1,513.39
13,2026-01-06,Pagamentos,23,0-30,ROBÔ,Jan,3,Q1,1,1229.62
19,2026-01-06,Pagamentos,2,91-120,ROBÔ,Jan,3,Q1,1,251.91
23,2026-01-06,Pagamentos,1,151-180,ROBÔ,Jan,3,Q1,1,38.74
...,...,...,...,...,...,...,...,...,...,...
223,2026-01-20,Pagamentos,9,151-180,ROBÔ,Jan,13,Q1,1,459.64
224,2026-01-20,Pagamentos,1,181-360,HUMANO,Jan,13,Q1,1,109.39
225,2026-01-20,Pagamentos,12,181-360,ROBÔ,Jan,13,Q1,1,826.77
226,2026-01-20,Pagamentos,2,361-720,HUMANO,Jan,13,Q1,1,99.97
228,2026-01-20,Pagamentos,1,Maior 720,HUMANO,Jan,13,Q1,1,47.42

In [146]:
from Getnet.src.data_wrangling_acionamentos import confere_tabulacao_acionamentos, acionamentos_unique_humano, enriquecer_acionamentos, acionamentos_esforco_humano, acionamentos_fxAtraso_origem_humano
df_acionamentos_tabulados = confere_tabulacao_acionamentos(df_tab_acionamentos, df_tabulacao_aciona)
df_acionamentos_tabulados

,DATA_ACIONA,HORA,CONTRATO_FIN,CPF_DEV,COD_ACIONA,DESC_ACIONAMENTO,COD_RECUP,NOME_RECUP,LOGIN_RECUP,ULTGRUPO_RECUP,...,VALORPRIN_FIN,STATCONT_FIN,DTDEVOL_FIN,DTENTRADA_FIN,CLASSIFICACAO_ACIONAMENTO,DESC_ACIONA,CPC,CPCA,PROMESSA,ACIONAMENTOS
0,2026-01-19,12:52:28.973333,30017503ID,13772282000197,5779,OUTROS-CRESOL,17275,ANDREZA LOPES,ANDREZA_RN,CRESOL,...,79.90,1,2023-02-02 16:29:45.740,2022-09-12 12:46:47.690,0,NaN,0,0,0,1
1,2026-01-14,08:55:32.200000,35940473ID,2465638343,8820,ATENDE E DESLIGA - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,...,547.58,0,NaT,2023-09-22 11:09:01.543,1,ATENDE E DESLIGA - GETNET,0,0,0,1
2,2026-01-08,09:20:49.956666,36251223ID,32590444000110,8914,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,...,716.39,0,NaT,2023-10-04 12:15:14.353,1,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,1,0,0,1
3,2026-01-12,09:40:35.740000,30082994ID,40881937000138,8820,ATENDE E DESLIGA - GETNET,19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,...,761.28,0,NaT,2023-12-29 12:03:48.800,1,ATENDE E DESLIGA - GETNET,0,0,0,1
4,2026-01-06,08:53:44.913333,30064441ID,46391479000135,4611,TEMPO EXCEDIDO (SEM MARCAÇÃO),19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,...,20664.58,0,NaT,2023-12-30 07:08:14.730,0,NaN,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,2026-01-02,13:56:31.460000,55038276ID,3010734816,8820,ATENDE E DESLIGA - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,...,189.80,0,NaT,2026-01-20 07:02:18.213,1,ATENDE E DESLIGA - GETNET,0,0,0,1
1613,2026-01-12,10:38:12.886666,55609042ID,34172985000235,7021,PROMESSA DE PAGAMENTO - GETNET,19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,...,184.91,0,NaT,2026-01-20 07:02:18.213,1,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1
1614,2026-01-08,08:46:13.493333,55043365ID,4864713812,7021,PROMESSA DE PAGAMENTO - GETNET,19083,CARLA FERNANDA VULCANIS,CARLA_GN,GETNET,...,79.90,0,NaT,2026-01-20 07:02:18.213,1,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1
1615,2026-01-20,11:39:50.773333,55726077ID,5650282862,4611,TEMPO EXCEDIDO (SEM MARCAÇÃO),19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,...,479.40,0,NaT,2026-01-20 07:02:18.213,0,NaN,0,0,0,1
1616,2026-01-20,10:43:39.993333,55726018ID,58525547000190,7028,DESCONHECE O CLIENTE - GETNET,19077,ALYFFE EDUARDO DE ANDRADE DE LIMA,ALYFFE_GN,None,...,579.75,0,NaT,2026-01-20 07:02:18.213,1,DESCONHECE O CLIENTE - GETNET,0,0,0,1

In [141]:
from Getnet.src.data_wrangling_acionamentos import confere_tabulacao_acionamentos, acionamentos_unique_humano, enriquecer_acionamentos, acionamentos_esforco_humano, acionamentos_fxAtraso_origem_humano

df_acionamentos_tabulados = confere_tabulacao_acionamentos(df_tab_acionamentos, df_tabulacao_aciona)
df_acionamentos_enriquecido, df_acion_semFaixa_humano, df_acion_semDescricao_humano, df_acion_semOrigem_humano = enriquecer_acionamentos(df_acionamentos_tabulados, df_mailing_hist_tratado, df_dw_calendario)
df_acionamentos_unique_humano = acionamentos_unique_humano(df_acionamentos_enriquecido, df_dw_calendario)
df_acionamentos_esforco_humano = acionamentos_esforco_humano(df_acionamentos_enriquecido, df_dw_calendario)
df_acionamentos_fxAtraso_origem_humano = acionamentos_fxAtraso_origem_humano(df_acionamentos_enriquecido, df_dw_calendario)
df_acionamentos_unique_humano

,DATA_ACIONA,FX_ATRASO,ORIGEM,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-02,Unique,HUMANO,0,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.00,1,Q1,1,Jan
1,2026-01-02,Unique,HUMANO,0,0.0,16.0,2302.63,8.0,1049.62,4.0,579.24,2.0,225.49,1,Q1,1,Jan
2,2026-01-02,Unique,HUMANO,0,0.0,28.0,4291.26,8.0,1107.28,4.0,608.19,1.0,159.80,1,Q1,1,Jan
3,2026-01-02,Unique,HUMANO,0,0.0,8.0,1098.27,3.0,421.40,0.0,0.00,0.0,0.00,1,Q1,1,Jan
4,2026-01-02,Unique,HUMANO,0,0.0,31.0,4634.34,10.0,1536.16,8.0,1219.14,0.0,0.00,1,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2026-01-19,Unique,HUMANO,0,0.0,94.0,23062.76,35.0,7688.54,18.0,3101.25,5.0,716.84,12,Q1,1,Jan
116,2026-01-19,Unique,HUMANO,0,0.0,92.0,25395.98,34.0,9245.40,25.0,5575.27,12.0,3182.99,12,Q1,1,Jan
117,2026-01-19,Unique,HUMANO,0,0.0,395.0,137337.30,135.0,41158.17,79.0,25588.80,15.0,4146.46,12,Q1,1,Jan
118,2026-01-19,Unique,HUMANO,0,0.0,131.0,55333.65,71.0,29218.29,38.0,12649.36,13.0,1451.31,12,Q1,1,Jan
119,2026-01-19,Unique,HUMANO,0,0.0,111.0,41445.96,57.0,18045.86,28.0,9215.86,5.0,545.70,12,Q1,1,Jan

In [142]:
from Getnet.src.utils import transformar_funil_formato_long, unir_dataframes

df_acionamentos_unique_humano = unir_dataframes(df_acionamentos_unique_humano, df_acionamentos_esforco_humano, df_acionamentos_fxAtraso_origem_humano)
df_acionamentos_unique_humano = transformar_funil_formato_long(df_acionamentos_unique_humano)
df_acionamentos_unique_humano

✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 360
✓ Total de colunas: 17
============================================================

,DATA,Indicador,qte,FX_ATRASO,ORIGEM,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN
0,2026-01-02,ACIONAMENTOS,16.0,0-30,HUMANO,Jan,1,Q1,1,2302.63
1,2026-01-02,CPC,8.0,0-30,HUMANO,Jan,1,Q1,1,1049.62
2,2026-01-02,CPCA,4.0,0-30,HUMANO,Jan,1,Q1,1,579.24
3,2026-01-02,PROMESSA,2.0,0-30,HUMANO,Jan,1,Q1,1,225.49
4,2026-01-02,TRABALHADO,0.0,0-30,HUMANO,Jan,1,Q1,1,0.00
...,...,...,...,...,...,...,...,...,...,...
1795,2026-01-19,TRABALHADO,0.0,Unique,HUMANO,Jan,12,Q1,1,0.00
1796,2026-01-19,TRABALHADO,0.0,Unique,HUMANO,Jan,12,Q1,1,0.00
1797,2026-01-19,TRABALHADO,0.0,Unique,HUMANO,Jan,12,Q1,1,0.00
1798,2026-01-19,TRABALHADO,0.0,Unique,HUMANO,Jan,12,Q1,1,0.00
1799,2026-01-19,TRABALHADO,0.0,Unique,HUMANO,Jan,12,Q1,1,0.00