In [1]:
%load_ext autoreload
%autoreload 2

# import sys 
# sys.path.append("..") 
import sys
sys.path.append(r"C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects")

In [48]:
import importlib 
#from utils import queries
#from utils.mailing import pipelines, metricas_acumuladas, data_processing
#from Renner.src.mailing import metricas_acumuladas, data_processing, pipelines
#from utils.acionamentos import metricas_acumuladas
from utils.discagens.expert import pipelines, data_processing, metricas_acumuladas
#from utils.acionamentos import pipelines, metricas_acumuladas
#from utils.pagamentos import pipelines, metricas_acumuladas, data_processing
#from utils import utils, config, queries
#from utils.digital_channels import data_processing, metricas_acumuladas
#from utils import queries, config
from Cresol.src import config, data_loader
#from Renner.src.mailing import data_processing, as
#from Renner.utils import queries

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
#importlib.reload(pipelines)
#importlib.reload(utils)
importlib.reload(metricas_acumuladas)
importlib.reload(data_processing)
importlib.reload(config)
#importlib.reload(data_loader)
#importlib.reload(queries)

In [3]:
# sobe para Projects 
from Cresol.src.data_loader import load_data_cresol

dados = load_data_cresol('2026-01-01', '2026-01-31')

(
df_discagens_expert,
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_whats
) = dados.values()

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/11] ✓ Discagens Expert: 965.316 registros (4m 38s)
[2/11] ✓ Mailing Histórico: 969.604 registros (5m 50s)
[3/11] ✓ Tabulação de Acionamentos: 37.395 registros (26s)
[4/11] ✓ Tabulação Acionamentos: 9.794 registros (0s)
[5/11] ✓ Calendário: 21 registros (0s)
[6/11] ✓ Pagamentos: 0 registros (2s)

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[7/11] ✓ Acordos: 1.892 registros (1s)
[8/11] ✓ SMS: 19.482 registros (0s)
[9/11] ✓ RCS: 20.211 registros (0s)
[10/11] ✓ Email: 0 registros (2s)

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[11/11] ✓ WhatsApp: 0 registros (0s)

✅ Carregamento concluído em 11m 3s
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [29]:
df_discagens_expert
df_mailing_hist
#df_discagens_expert.shape
# Converte a visão de valores em uma lista e acessa o primeiro
# df = list(df_discagens_expert)[0]

# print(df.shape)
# df.info()


# Se você usou algo como: dfs_dit = pd.read_excel('arquivo.xlsx', sheet_name=None)
# Para iterar e identificar cada um:

,DATA,CONTRATO,CPF,ID_CAR,ATRASO,COD_CLI,VALOR
0,2026-01-01,500106120230208686,39094855968,89.0,19,181,18664.94
1,2026-01-01,500201220250178977,3348095921,91.0,14,231,91312.78
2,2026-01-01,500104920250609529,93416237900,89.0,16,181,213.70
3,2026-01-01,500108920250304200,78251737249,89.0,38,181,31405.56
4,2026-01-01,500109720250157973,70802135170,89.0,27,181,10717.88
...,...,...,...,...,...,...,...
969599,2026-01-29,500201220250166758,4498986954,91.0,19,231,5752.18
969600,2026-01-29,500103820240830626,26626002848,89.0,1092,181,32375.69
969601,2026-01-29,500103820241539630,3832786511,89.0,2856,181,661137.36
969602,2026-01-29,500103820240746293,93292406587,89.0,815,181,54.96
969603,2026-01-29,500100320260007943,13137979951,89.0,110,181,12785.53

In [30]:
from utils.mailing.pipelines import processar_mailing_completo
from Cresol.src.mailing.data_processing import add_pf_pj, add_pa
from Cresol.src.config import LOG_MAILING, segmentacoes_extras

df_mailing_analitico, df_mailing_acumulado = processar_mailing_completo(
    df_mailing_hist,
    df_dw_calendario,
    segmentacoes=segmentacoes_extras,
    tratamentos_extras=[
        add_pf_pj,
        add_pa,
    ],
    arquivo_log=LOG_MAILING,
)
df_mailing_analitico

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 462
✓ Total de colunas: 10
============================================================

,DATA,CONTRATO,CPF,ID_CAR,ATRASO,COD_CLI,VALOR,PF_PJ,PA
0,2026-01-01,500106120230208686,39094855968,89.0,19,181,18664.94,PF,CRESOL BASER
1,2026-01-01,500201220250178977,3348095921,91.0,14,231,91312.78,PF,CRESOL SICOPER CALLCENTER
2,2026-01-01,500104920250609529,93416237900,89.0,16,181,213.70,PF,CRESOL BASER
3,2026-01-01,500108920250304200,78251737249,89.0,38,181,31405.56,PF,CRESOL BASER
4,2026-01-01,500109720250157973,70802135170,89.0,27,181,10717.88,PF,CRESOL BASER
...,...,...,...,...,...,...,...,...,...
969599,2026-01-29,500201220250166758,4498986954,91.0,19,231,5752.18,PF,CRESOL SICOPER CALLCENTER
969600,2026-01-29,500103820240830626,26626002848,89.0,1092,181,32375.69,PF,CRESOL BASER
969601,2026-01-29,500103820241539630,3832786511,89.0,2856,181,661137.36,PF,CRESOL BASER
969602,2026-01-29,500103820240746293,93292406587,89.0,815,181,54.96,PF,CRESOL BASER
969603,2026-01-29,500100320260007943,13137979951,89.0,110,181,12785.53,PF,CRESOL BASER

In [14]:
df_analitico
#df_acumulado_mailing
df_discagens_expert

,DATA,ID_DISCAGEM,CONTRATO,CPF,AGENTE,DDD,TELEFONE,DATA_ENCERRAMENTO,CAMPANHA,COD_SIP,CLASS_RETORNO,DESC_MOTIVO_ENCERR
0,2026-01-05,15,500100820250081873,4197996993,,45,999239949,2026-01-05 09:47:04,4304,200,cxpos,bloqueiodetector
1,2026-01-05,26,500103820250221971,94057427104,,74,981015225,2026-01-05 09:47:04,4304,200,cxpos,bloqueiodetector
2,2026-01-05,136,500103820240957262,730899586,,75,991897713,2026-01-05 09:47:09,4786,200,cxpre,bloqueiodetector
3,2026-01-05,210,500203320240346748,78685737087,,51,996799584,1899-12-30 00:00:00,4304,408,cxpre,bloqueiodetector
4,2026-01-05,246,500103820241676382,59253029587,,11,946080245,1899-12-30 00:00:00,4786,480,,foneforadeservico
...,...,...,...,...,...,...,...,...,...,...,...,...
965311,2026-01-30,49434253,500204420220017811,6340726925,,49,999940743,1899-12-30 00:00:00,4786,,cxpre,bloqueiodetector
965312,2026-01-30,49434398,500103820241540273,23989130587,,75,999664096,2026-01-30 17:49:48,4786,200,silencio,bloqueiodetector
965313,2026-01-30,49434614,500103820240230199,58060278568,,75,32722358,1899-12-30 00:00:00,4786,480,,foneforadeservico
965314,2026-01-30,49435006,500204520220098842,62458256015,,55,999991519,1899-12-30 00:00:00,4786,408,,naoatende
965315,2026-01-30,49435216,500103820240691408,5490266570,,43,984154081,1899-12-30 00:00:00,4786,480,,foneforadeservico

In [31]:
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens

df_discagens_analitico, df_discagens_sem_relacionamento = aplicar_transformacoes_discagens(
    df=df_discagens_expert,
    config=TRANSFORMACOES_DISCAGENS,
    df_mailing=df_mailing_analitico,
    df_calendario=df_dw_calendario,
    segmentacoes_extras=segmentacoes_extras,
    arquivo_log=LOG_DISCAGENS,
)
df_discagens_analitico

,DATA,ID_DISCAGEM,CONTRATO,AGENTE,DDD,TELEFONE,DATA_ENCERRAMENTO,CAMPANHA,COD_SIP,CLASS_RETORNO,...,ATRASO,COD_CLI,VALOR,PF_PJ,PA,CPF,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,15,500100820250081873,,45,999239949,2026-01-05 09:47:04,4304,200,cxpos,...,87.0,181.0,14166.63,PF,CRESOL BASER,4197996993,2,Q1,1,Jan
1,2026-01-05,26,500103820250221971,,74,981015225,2026-01-05 09:47:04,4304,200,cxpos,...,82.0,181.0,14934.00,PF,CRESOL BASER,94057427104,2,Q1,1,Jan
2,2026-01-05,136,500103820240957262,,75,991897713,2026-01-05 09:47:09,4786,200,cxpre,...,2294.0,181.0,57401.89,PF,CRESOL BASER,730899586,2,Q1,1,Jan
3,2026-01-05,210,500203320240346748,,51,996799584,1899-12-30 00:00:00,4304,408,cxpre,...,83.0,230.0,13205.55,PF,CRESOL SICOPER,78685737087,2,Q1,1,Jan
4,2026-01-05,246,500103820241676382,,11,946080245,1899-12-30 00:00:00,4786,480,,...,3511.0,181.0,112941.29,PF,CRESOL BASER,59253029587,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965311,2026-01-30,49434253,500204420220017811,,49,999940743,1899-12-30 00:00:00,4786,,cxpre,...,44.0,231.0,981.61,PF,CRESOL SICOPER CALLCENTER,6340726925,21,Q1,1,Jan
965312,2026-01-30,49434398,500103820241540273,,75,999664096,2026-01-30 17:49:48,4786,200,silencio,...,3152.0,181.0,146052.65,PF,CRESOL BASER,23989130587,21,Q1,1,Jan
965313,2026-01-30,49434614,500103820240230199,,75,32722358,1899-12-30 00:00:00,4786,480,,...,6037.0,181.0,31475.54,PF,CRESOL BASER,58060278568,21,Q1,1,Jan
965314,2026-01-30,49435006,500204520220098842,,55,999991519,1899-12-30 00:00:00,4786,408,,...,42.0,231.0,936.60,PF,CRESOL SICOPER CALLCENTER,62458256015,21,Q1,1,Jan
965315,2026-01-30,49435216,500103820240691408,,43,984154081,1899-12-30 00:00:00,4786,480,,...,3566.0,181.0,168884.20,PF,CRESOL BASER,5490266570,21,Q1,1,Jan

In [47]:
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.metricas_acumuladas import processar_acumulados_discagens_completo

df_discagens_acumulado = processar_acumulados_discagens_completo(
    df_discagens=df_discagens_analitico,
    segmentacoes_extras=segmentacoes_extras,
    retorno='consolidado',
    arquivo_log=LOG_DISCAGENS
)
df_discagens_acumulado

TypeError: processar_acumulados_discagens_completo() missing 1 required positional argument: 'df_dw_calendario'

In [42]:
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.metricas_acumuladas import processar_acumulados_discagens

df_discagens_acumulado = processar_acumulados_discagens(
    df_discagens=df_discagens_analitico,
    segmentacoes=segmentacoes_extras,
    retorno='consolidado',
    arquivo_log=LOG_DISCAGENS
)
df_discagens_acumulado

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 240
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 240
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 480
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-05,Trabalhado,53,PF,ASCOOB CRESOL,Jan,2,Q1,1,3.514587e+05,Funil
1,2026-01-05,Trabalhado,426,PF,CENTRAL BRASIL EXTRA,Jan,2,Q1,1,8.214105e+06,Funil
2,2026-01-05,Trabalhado,7539,PF,CRESOL BASER,Jan,2,Q1,1,6.536391e+08,Funil
3,2026-01-05,Trabalhado,199,PF,CRESOL SICOPER,Jan,2,Q1,1,1.959359e+07,Funil
4,2026-01-05,Trabalhado,555,PF,CRESOL SICOPER CALLCENTER,Jan,2,Q1,1,8.341752e+06,Funil
...,...,...,...,...,...,...,...,...,...,...,...
475,2026-01-26,Trabalhado,56687,Esforço,Esforço,Jan,17,Q1,1,1.752704e+09,Daily
476,2026-01-27,Trabalhado,46481,Esforço,Esforço,Jan,18,Q1,1,3.157770e+09,Daily
477,2026-01-28,Trabalhado,44294,Esforço,Esforço,Jan,19,Q1,1,2.971129e+09,Daily
478,2026-01-29,Trabalhado,44804,Esforço,Esforço,Jan,20,Q1,1,3.483884e+09,Daily
479,2026-01-30,Trabalhado,42035,Esforço,Esforço,Jan,21,Q1,1,2.925902e+09,Daily