In [2]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> GERAR DADOS

# import importlib
# importlib.reload(queries)
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.db_connection import get_connection
from queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario
import pandas as pd

# DADOS SRC
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
df_discagens_expert = pd.read_sql(
    get_query_discagens('2025-09-01', '2025-09-30'), 
    conn_src
)
df_cad_devf = pd.read_sql(
    get_query_cad_devf(), 
    conn_src
)
df_tab_acionamentos = pd.read_sql(
    get_query_base_acionamentos('2025-09-01', '2025-09-30'), 
    conn_src
)

# DADOS BD2/PLANEJAMENTO
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
df_maling_hist = pd.read_sql(
    get_query_mailing_hist('2025-09-01', '2025-09-30'), 
    conn_bd2
)
df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)

df_dw_calendario = pd.read_sql(
    get_query_dw_calendario(), 
    conn_bd2
)
df_tabulacao_aciona = pd.read_sql(
    get_query_tabulacao_aciona(), 
    conn_bd2
)

# DADOS BD2/TRC
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
df_discagens_trestto = pd.read_sql(
    get_query_discagens_trestto('2025-09-01', '2025-09-30'), 
    conn_trc
)

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_discagens_expert = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cad_devf = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tab_acionamentos = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_maling_hist = pd.read_sql(

📊 Antes do join - Mailing: 6,255,364 | CAD_DEVF: 3,003,398
📊 Após join: 6,255,364
📊 Contratos com valor: 6,248,734
📊 Contratos sem valor: 6,630

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tabulacao_aciona = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_8516\752579391.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_discagens_trestto = pd.read_sql(

In [110]:
from src import data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert, utils
import importlib
import queries
importlib.reload(utils)
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(queries)

In [108]:
#print(len(df_enriquecido_discagens_trestto_semFaixa))
df_acion_semFaixa_humano

,DATA_ACIONA,HORA,CONTRATO_FIN,CPF_DEV,COD_ACIONA,DESC_ACIONAMENTO,COD_RECUP,NOME_RECUP,LOGIN_RECUP,ULTGRUPO_RECUP,COD_CLI,VALORPRIN_FIN,STATCONT_FIN,DTDEVOL_FIN,DTENTRADA_FIN,CLASSIFICACAO_ACIONAMENTO,DESC_ACIONA,CPC,CPCA,PROMESSA,ACIONAMENTOS,ORIGEM,FX_ATRASO,nr_dia_util,quartil,dt_mes,mes_abreviado
19,2025-09-01,00:00:00,30839377ID,29647070000118,7077,ENVIO DE SMS - GETNET,17987,MAYARA MILIANTE,MAYARA.MILIANTE,None,228,28.00,1,2024-12-23 16:49:28.507,2024-12-07 07:10:30.930,1,ENVIO DE SMS - GETNET,0,0,0,1,HUMANO,NaN,1,Q3,9,Set
60,2025-09-01,00:00:00,34461139ID,30134147000216,7077,ENVIO DE SMS - GETNET,17987,MAYARA MILIANTE,MAYARA.MILIANTE,None,228,1086.44,1,2024-05-24 12:01:42.443,2023-06-13 19:19:36.743,1,ENVIO DE SMS - GETNET,0,0,0,1,HUMANO,NaN,1,Q3,9,Set
61,2025-09-01,00:00:00,34461699ID,30134147000216,7077,ENVIO DE SMS - GETNET,17987,MAYARA MILIANTE,MAYARA.MILIANTE,None,228,5286.44,1,2024-12-23 16:49:33.933,2024-04-20 08:03:01.163,1,ENVIO DE SMS - GETNET,0,0,0,1,HUMANO,NaN,1,Q3,9,Set
99,2025-09-01,00:00:00,39807132ID,29647070000118,7077,ENVIO DE SMS - GETNET,17987,MAYARA MILIANTE,MAYARA.MILIANTE,None,228,539.76,0,NaT,2025-10-06 20:01:40.673,1,ENVIO DE SMS - GETNET,0,0,0,1,HUMANO,NaN,1,Q3,9,Set
109,2025-09-01,00:00:00,40684878ID,12778220000120,7077,ENVIO DE SMS - GETNET,17987,MAYARA MILIANTE,MAYARA.MILIANTE,None,228,779.40,0,NaT,2025-10-06 20:01:40.673,1,ENVIO DE SMS - GETNET,0,0,0,1,HUMANO,NaN,1,Q3,9,Set
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11247,2025-09-24,10:30:12.526666,44845005ID,29356945000203,4611,TEMPO EXCEDIDO (SEM MARCAÇÃO),17342,ELIS REGINA DE MELO SILVA,ELIS_GN,GETNET,228,273.20,1,2025-10-07 15:02:36.733,2025-10-06 20:05:35.290,0,NaN,0,0,0,1,HUMANO,NaN,18,Q3,9,Set
11298,2025-09-30,13:42:46.523333,48408082ID,47180921000147,7021,PROMESSA DE PAGAMENTO - GETNET,17348,LUIZ FERNANDO ROSARIO DE LIMA,LUIZ_GN,GETNET,228,64.43,1,2025-10-16 07:02:35.553,2025-10-15 07:01:59.973,1,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1,HUMANO,NaN,22,Q3,9,Set
11312,2025-09-26,12:57:21.036666,34899038ID,37677825000155,7026,SEM PREVISÃO DE PAGAMENTO - GETNET,17342,ELIS REGINA DE MELO SILVA,ELIS_GN,GETNET,228,159.80,1,2025-11-01 07:02:58.460,2025-10-17 07:04:03.913,1,SEM PREVISÃO DE PAGAMENTO - GETNET,1,1,0,1,HUMANO,NaN,20,Q3,9,Set
11370,2025-09-27,12:43:43.903333,50739058ID,13893221000188,9387,GETNET ACORDO CANCELADO - NÃO RETORNA OBJETO,17348,LUIZ FERNANDO ROSARIO DE LIMA,LUIZ_GN,GETNET,228,21.30,1,2025-11-01 07:02:58.460,2025-10-24 07:01:50.093,1,GETNET ACORDO CANCELADO - NÃO RETORNA OBJETO,1,0,0,1,HUMANO,NaN,20,Q3,9,Set
11380,2025-09-30,11:02:42.750000,53241708ID,56125794000174,7021,PROMESSA DE PAGAMENTO - GETNET,17755,BRUNO CURUCA LOURENCAO,BRUNO_RN,GETNET,228,129.90,0,NaT,2025-10-25 07:01:38.427,1,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1,HUMANO,NaN,22,Q3,9,Set

In [111]:
from src.utils import acionamentos_funil
df_acionamentos_funil, df_analitico_acionamentos_humano, df_acion_semFaixa_humano, df_acion_semDescricao_humano, df_acion_semOrigem_humano, df_analitico_trestto, df_enriquecido_discagens_trestto_semFaixa, df_analitico_expert, df_enriquecido_discagens_expert_semFaixa, df_humano_tabulados_como_robo, df_dicagens_operacaoOutros = acionamentos_funil(df_tab_acionamentos, df_tabulacao_aciona, df_dw_calendario, df_maling_hist, df_discagens_trestto, df_discagens_expert)

df_acionamentos_funil

✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 720
✓ Total de colunas: 17
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 1,560
✓ Total de colunas: 17
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 750
✓ Total de colunas: 17
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 3,030
✓ Total de colunas: 17
============================================================

,DATA,FX_ATRASO,ORIGEM,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2025-09-01,Preventivo,HUMANO,0.0,0.00,2.0,260.58,2.0,260.58,0.0,0.00,0.0,0.00,1,Q3,9,Set
1,2025-09-01,0-30,HUMANO,0.0,0.00,32.0,1885.71,17.0,951.23,9.0,504.66,4.0,272.63,1,Q3,9,Set
2,2025-09-01,31-60,HUMANO,0.0,0.00,4.0,117.18,2.0,114.86,1.0,56.26,0.0,0.00,1,Q3,9,Set
3,2025-09-01,61-90,HUMANO,0.0,0.00,2.0,3835.80,0.0,0.00,0.0,0.00,0.0,0.00,1,Q3,9,Set
4,2025-09-01,91-120,HUMANO,0.0,0.00,9.0,18682.87,1.0,59.80,1.0,59.80,0.0,0.00,1,Q3,9,Set
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3025,2025-09-30,121-150,Robô,20515.0,3811458.96,3454.0,580734.86,552.0,81655.00,524.0,78112.48,173.0,17884.49,22,Q3,9,Set
3026,2025-09-30,151-180,Robô,13287.0,3595799.02,1884.0,495234.98,289.0,69372.50,271.0,66075.28,81.0,11234.70,22,Q3,9,Set
3027,2025-09-30,181-360,Robô,903.0,282433.08,90.0,23129.94,11.0,2351.52,11.0,2351.52,2.0,263.82,22,Q3,9,Set
3028,2025-09-30,361-720,Robô,182.0,81472.10,14.0,5462.24,6.0,2468.01,6.0,2468.01,0.0,0.00,22,Q3,9,Set
3029,2025-09-30,Maior 720,Robô,51.0,19394.93,8.0,2510.41,2.0,1191.53,2.0,1191.53,0.0,0.00,22,Q3,9,Set

In [9]:
# INTERSEÇÃO DE CPFS DISCADOS COM E SEM FAIXA DE ATRASO

from src.data_wrangling_discagens_trestto import tratar_discagens_trestto, enriquecer_discagens_trestto, acionamentos_esforco_trestto, interseção_cpfs_discados_trestto

mesagem_resultado = interseção_cpfs_discados_trestto(df_enriquecido_discagens_trestto_limpo, df_enriquecido_discagens_trestto_semFaixa)
mesagem_resultado

📦 CPFs únicos COM FX_ATRASO: 117,039
📦 CPFs únicos SEM FX_ATRASO: 202,507
--------------------------------------------------
📊 Resultados da Comparação de CPFs Únicos

CPFs em AMBOS os grupos (Intersecção): 21,144
-------------------------
CPFs SOMENTE no grupo COM FX_ATRASO: 95,895
CPFs SOMENTE no grupo SEM FX_ATRASO: 181,363

In [49]:
from src import data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert
import importlib
import queries
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(queries)

In [107]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_dicagens_operacaoOutros.to_csv('df_dicagens_operacaoOutros.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_dicagens_operacaoOutros.csv')  # abre com o programa padrão

In [52]:
print(len(df_humano_tabulados_como_robo))
print(len(df_dicagens_operacaoOutros))
print(len(df_enriquecido_discagens_expert_limpo))

2408
68202
2681611

In [83]:
from src import data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert
import importlib
import queries
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(queries)

In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> TRATAMENTO DOS DADOS
from src.data_wrangling_discagens_expert import tratar_base_discagens
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.data_wrangling_discagens_trestto import tratar_discagens_trestto
from src.data_wrangling_acionamentos import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos, acionamentos_unique_fxAtraso, acionamentos_unique_origem_fxAtraso, acionamentos_esforco_origem_fxAtraso

# Aplicar tratamento
# SEGMENTAÇÃO TIPO DE OPERAÇÃO, ADICIONAR DDD
df_discagens_expert = tratar_base_discagens(df_discagens_expert)
# ADICIONAR PRODUTO, FAIXA DE ATRASO E VALOR PRINCIPAL
#df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
# DATA FRAMES ESFORÇO, ÚNICOS TRATADOS, COM BASE NA MAILING HIST
df_trestto_esforco, df_trestto_unique = tratar_discagens_trestto(
    df_discagens_trestto, 
    df_maling_hist
)
# CONVERTE VALORES DE DISCAGENS PARA INT
df_tabualacao_aciona = tratar_acionamentos_tabulacao(df_tabulacao_aciona)
df_mailing_hist_cruz = tratar_base_discagens(df_maling_hist)

# CONFERIR TABULAÇÃO AOS ACIONAMENTOS E ENRIQUECIMENTO
df_acionamentos_tabulados = confere_tabulacao_acionamentos(df_tab_acionamentos, df_tabualacao_aciona)
df_acionamentos_enriquecido = enriquecer_acionamentos(df_acionamentos_tabulados, df_maling_hist, df_discagens_expert, df_dw_calendario)
df_acionamentos_unique_fxAtraso = acionamentos_unique_fxAtraso(df_acionamentos_enriquecido, df_dw_calendario)
df_acionamentos_unique_origem_fxAtraso = acionamentos_unique_origem_fxAtraso(df_acionamentos_enriquecido, df_dw_calendario)
# AGRUPAMENTO E CONTAGEM DE CPFs ÚNICOS POR MÉTRICA
df_acionamentos_esforco_origem_fxAtraso = acionamentos_esforco_origem_fxAtraso(df_acionamentos_enriquecido, df_dw_calendario)

# print(f"✓ Esforço diário: {len(df_trestto_esforco)} dias")
# print(df_trestto_esforco.head())

# print(f"\n✓ Únicos diário: {len(df_trestto_unique)} dias")
# print(df_trestto_unique.head())

📊 Antes da consolidação - Trestto: 2,762,568
📊 Após consolidação - Trestto: 2,648,475
📊 Mailing: 6,255,364
📊 Após join: 1,169,157

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_wrangling_discagens_trestto.py:39: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_esforco = df_join.groupby(['DATA', 'PRODUTO', 'FX_ATRASO'], as_index=False)[colunas_metricas].sum()
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_wrangling_discagens_trestto.py:49: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_unique = df_unique.groupby(['DATA', 'PRODUTO', 'FX_ATRASO'], as_index=False)[colunas_metricas].sum()

In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>> TESTES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# tipo da coluna
# >>>>>>>>>>>>>>>>>>>>>>> VERIFICAR TIPO DE DADO DE UMA COLUNA ESPECÍFICA
#print(df_discagens['ddd'].dtype)
# primeiros valores (mostra índices também)
#df_discagens['ddd'].head(30)

# >>>>>>>>>>>>>>>>>>>>>>> MOSTRAR PARTE DO DATAFRAME
# df_discagens.head()

# >>>>>>>>>>>>>>>>>>>>>>> FILTRAR DADOS DE UMA COLUNA ESPECÍFICA
# df_ativo = df_mailing_hist[df_mailing_hist['ID_CAR'].notna()]
# df_ativo.head()

# import pandas as pd
# Supondo que seu DataFrame seja 'df'

# valores_unicos = df_cad_devf['DESC_CAR'].unique()
# print(valores_unicos)

# >>>>>>>>>>>>>>>>>>>>>>> CONTAR VALORES ÚNICOS DE UMA COLUNA ESPECÍFICA
# len(df_ativo)
# df_discagens['OPERACAO'].value_counts().reset_index().rename(columns={'index': 'OPERACAO', 'OPERACAO': 'QTD'})
#  print(filtro)
#len(df_discagens)
#print("Linhas:", df_discagens.shape[0], " | Colunas:", df_discagens.shape[1])
#df_discagens.columns.tolist()
#df_discagens['Agente'].unique()
#type(df_discagens)

# >>>>>>>>>>>>>>>>>>>>>>> resumo por estado
# df_resumo = (
#     df_discagens
#     .groupby('ESTADO')['CPF']
#     .nunique()
#     .reset_index()
#     .rename(columns={'CPF': 'QTD_CPF_DISTINTOS'})
#     .sort_values(by='QTD_CPF_DISTINTOS', ascending=False)
# )
# df_resumo.head()
# print(df_resumo)
# >>>>>>>>>>>>>>>>>>>>>>>>>>> TESTANDO AS CONEXÕES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# server = os.getenv('SERVER_BD2')
# database = os.getenv('DATABASE_TRC')
# print(f"Valor do Servidor: {server}")
# print(f"Valor do Banco de Dados: {database}") 

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> RECARREGANDO O .ENV <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
# from dotenv import load_dotenv
# import os

# # Recarrega o .env
# load_dotenv(dotenv_path='.env', override=True)

# # Testa se as variáveis foram carregadas
# print(os.getenv("SERVER_BD2"))
# print(os.getenv("DATABASE_TRC"))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> AGRUPANDO DADOS COM SOMA (TRESTTO) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
#df_discagens_trestto = df_discagens_trestto.groupby('DATA')['ALO'].sum().reset_index()


# data_inicial = '2025-09-30'
# data_final = '2025-09-30'

# Filtrar entre datas
# df_discagens_trestto_sum = df_discagens_trestto_sum[(df_discagens_trestto_sum['DATA'] >= data_inicial) & (df_discagens_trestto_sum['DATA'] <= data_final)]

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FECHANDO AS CONEXÕES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
# if 'conn' in locals() and conn:
#     conn.close()
#     print("Conexão com o banco de dados fechada com sucesso.")