In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> GERAR DADOS

# import importlib
# importlib.reload(queries)
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.db_connection import get_connection
from queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd

# DADOS SRC

def data_loader(conn_trc, conn_bd2, conn_src):

    df_discagens_expert = pd.read_sql(
        get_query_discagens('2025-09-01', '2025-09-30'), 
        conn_src
    )
    df_cad_devf = pd.read_sql(
        get_query_cad_devf(), 
        conn_src
    )
    df_tab_acionamentos = pd.read_sql(
        get_query_base_acionamentos('2025-09-01', '2025-09-30'), 
        conn_src
    )

    # DADOS BD2/PLANEJAMENTO
    df_maling_hist = pd.read_sql(
        get_query_mailing_hist('2025-09-01', '2025-09-30'), 
        conn_bd2
    )
    df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)

    df_dw_calendario = pd.read_sql(
        get_query_dw_calendario(), 
        conn_bd2
    )
    df_tabulacao_aciona = pd.read_sql(
        get_query_tabulacao_aciona(), 
        conn_bd2
    )

    df_pagamentos = pd.read_sql(
        get_query_pagamentos('2025-09-01', '2025-09-30'), 
        conn_src
    )
    df_acordos = pd.read_sql(
        get_query_acordos('2025-09-01', '2025-09-30'), 
        conn_src
    )

    # DADOS BD2/TRC
    
    df_discagens_trestto = pd.read_sql(
        get_query_discagens_trestto('2025-09-01', '2025-09-30'), 
        conn_trc
    )
    
    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

def get_connection():
    conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
    conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
    conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

    df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto = data_loader(conn_trc, conn_bd2, conn_src)

    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_discagens_expert = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cad_devf = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tab_acionamentos = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_maling_hist = pd.read_sql(

📊 Antes do join - Mailing: 6,255,364 | CAD_DEVF: 3,003,504
📊 Após join: 6,255,364
📊 Contratos com valor: 6,248,734
📊 Contratos sem valor: 6,630

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:37: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tabulacao_aciona = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_12096\95884538.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_discagens_trestto = pd.read_sql(

In [215]:
from src.data_loader import load_all_data

dados = load_all_data()

# Acessa individualmente por índice
df_expert_teste = dados[0]
df_expert_teste

📂 Lendo arquivo: \\trc-dc-ad\Planejamento\MIS\CARTEIRAS\GetNet\df_csvBI_padronizado.csv
⚠️ Coluna 'data' não encontrada. Usando primeira coluna: 'data;Indicador;qte;fx_atraso;tipo;MesAbreviado;nr_dia_util;quartil;dt_mes;VALORPRIN_FIN'
❌ Erro ao processar CSV: Nenhuma data válida encontrada após 2020
⚠️ Usando datas padrão.
🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2025-11-01 até 2025-11-13...

⏳ Carregando discagens_expert...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:165: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cad_devf = pd.read_sql(

   ✓ 572001 registros
⏳ Carregando cad_devf...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:172: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tab_acionamentos = pd.read_sql(

   ✓ 3003560 registros
⏳ Carregando tab_acionamentos...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_pagamentos = pd.read_sql(

   ✓ 2710 registros
⏳ Carregando pagamentos...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:186: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_acordos = pd.read_sql(

   ✓ 9716 registros
⏳ Carregando acordos...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:193: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  print("⏳ Carregando mailing_hist...")

   ✓ 1548 registros
⏳ Carregando mailing_hist...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:201: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)

   ✓ 3301976 registros (antes do tratamento)
⏳ Tratando base mailing_hist...
📊 Antes do join - Mailing: 3,301,976 | CAD_DEVF: 3,003,560
📊 Após join: 3,301,976
📊 Contratos com valor: 3,301,976
📊 Contratos sem valor: 0
   ✓ 3301976 registros (após tratamento)
⏳ Carregando dw_calendario...
   ✓ 365 registros
⏳ Carregando tabulacao_aciona...
   ✓ 79 registros
⏳ Carregando discagens_trestto...

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:212: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tabulacao_aciona = pd.read_sql(
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  print("⏳ Carregando discagens_trestto...")
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.

   ✓ 1639347 registros

✅ Todos os dados carregados com sucesso!

🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

,DATA,id,CONTRATO,CPF,ddd,fone,GrupoPrincipal,UltCodSigRecPublica,ResultadoClassificacao,MotivoEncerramentoBilhete,Instante200OKPub,Agente,tempoconversacao_ms,codtabulacao
0,2025-11-01,5,,,81,991976414,4017,,,abandonomfila,2025-11-01 07:19:46,,0,None
1,2025-11-01,6,,,81,991976414,4017,,,abandonomfila,2025-11-01 07:39:30,,0,None
2,2025-11-01,13,50670257id,14810475000158,82,988645462,4118,404,,foneinexistente,1899-12-30 00:00:00,,0,None
3,2025-11-01,14,52228777id,54175565000139,16,997257060,4118,480,,foneforadeservico,1899-12-30 00:00:00,,0,None
4,2025-11-01,91,44012055id,37305726000142,15,998165444,4047,480,cxpre,bloqueiodetector,1899-12-30 00:00:00,,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571996,2025-11-14,21248413,42917981id,52704591000181,91,984507028,4852,200,cxpre,bloqueiodetector,2025-11-14 17:26:05,,0,None
571997,2025-11-14,21248437,41992186id,16481150809,11,972977929,4118,200,cxpre,bloqueiodetector,2025-11-14 17:26:08,,0,None
571998,2025-11-14,21248445,41254874id,5292759708,21,999476747,4852,200,cxpos,bloqueiodetector,2025-11-14 17:26:09,,0,None
571999,2025-11-14,21248464,41947840id,53892215000120,11,970333394,4118,200,cxpos,bloqueiodetector,2025-11-14 17:26:04,,0,None
572000,2025-11-14,21248466,40760387id,5278728655,32,988768788,4852,200,cxpos,bloqueiodetector,2025-11-14 17:26:05,,0,None

In [223]:
df_expert = dados[0]
df_cad_devf = dados[1]
df_tab_acionamentos = dados[2]
df_maling_hist = dados[3]
df_dw_calendario = dados[4]
df_tabulacao_aciona = dados[5]
df_pagamentos = dados[6]
df_acordos = dados[7]
df_discagens_trestto = dados[8]

df_acordos

,DATA_ACORDO,HORA_ACORDO,CPF_DEV,CONTRATO_FIN,CANC_ACORDO,NACORDO_ACO,VLRACORDO_ACO,VALORPRIN_FIN,DTDEVOL_FIN,TIPO
0,2025-11-13,14:20:15.003333,48136565104,35924557ID,None,1,59.80,119.60,NaT,HUMANO
1,2025-11-06,08:58:58.160000,46444138000180,41847158ID,2025-11-14,1,56.67,87.77,2025-11-13 07:02:39.820,HUMANO
2,2025-11-01,09:55:31.350000,51962644000100,40203015ID,2025-11-11,3,236.29,972.67,2025-11-10 07:02:36.910,HUMANO
3,2025-11-04,10:07:05.216666,54004907000158,43386451ID,2025-11-14,1,77.70,89.70,2025-11-13 07:02:39.820,HUMANO
4,2025-11-10,09:18:56.196666,11721603000107,30409456ID,None,2,203.26,777.13,NaT,HUMANO
...,...,...,...,...,...,...,...,...,...,...
1543,2025-11-01,08:41:33.223333,35294122000112,54008280ID,2025-11-10,1,87.75,74.74,NaT,ROBÔ
1544,2025-11-01,10:28:55.480000,37514225000176,53864651ID,2025-11-10,1,36.00,29.90,NaT,ROBÔ
1545,2025-11-01,13:14:21.823333,53674453000160,54279230ID,2025-11-10,1,78.27,226.80,NaT,ROBÔ
1546,2025-11-01,12:51:54.100000,60442450000166,53989490ID,2025-11-10,1,36.00,29.90,NaT,ROBÔ
1547,2025-11-01,10:35:24.386666,60485727000138,53989075ID,2025-11-10,1,36.00,29.90,NaT,ROBÔ

In [210]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_csvBI_padronizado.to_csv('df_csvBI_padronizado.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_csvBI_padronizado.csv')  # abre com o programa padrão

In [209]:
from src.csv_cleaning import tratar_base_csv

df_csvBI_padronizado = tratar_base_csv()
df_csvBI_padronizado

============================================================
✓ 4 DataFrames unidos com sucesso
✓ Total de linhas: 28,546
✓ Total de colunas: 10
============================================================

,data,Indicador,qte,fx_atraso,tipo,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN
0,01/01/2025,Pagamentos,82.0,0 - 0-30,HUMANO,jan,1,Q1,1,8583.13
1,01/01/2025,Pagamentos,0.0,0 - 0-30,HUMANO,jan,2,Q1,1,0.00
2,01/01/2025,Pagamentos,0.0,0 - 0-30,HUMANO,jan,3,Q1,1,0.00
3,01/01/2025,Pagamentos,0.0,0 - 0-30,HUMANO,jan,4,Q1,1,0.00
4,01/01/2025,Pagamentos,0.0,0 - 0-30,HUMANO,jan,5,Q1,1,0.00
...,...,...,...,...,...,...,...,...,...,...
28541,31/10/2025,Trabalhado,109.0,7 - 361-720,ROBÔ,out,23,Q4,10,0.00
28542,31/10/2025,Trabalhado,8221.0,8 - Maior 720,HUMANO,out,23,Q4,10,0.00
28543,31/10/2025,Trabalhado,28.0,8 - Maior 720,ROBÔ,out,23,Q4,10,0.00
28544,31/10/2025,Trabalhado,68663.0,GERAL,HUMANO,out,23,Q4,10,0.00
28545,31/10/2025,Trabalhado,95315.0,GERAL,ROBÔ,out,23,Q4,10,0.00

In [214]:
from src import utils, data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert, csv_cleaning, data_loader
import importlib
import queries
importlib.reload(utils)
importlib.reload(csv_cleaning)
importlib.reload(data_loader)
importlib.reload(csv_cleaning)
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(queries)

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_loader.py:249: SyntaxWarning: invalid escape sequence '\P'

In [ ]:
from src.data_wrangling_mailingHist import gerar_acumulado_mailing_hist, gerar_acumulado_maling_hist_unique

df_mailing_acumulado = gerar_acumulado_mailing_hist(df_maling_hist, df_dw_calendario)
df_mailing_acumulado

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 660
✓ Total de colunas: 9
============================================================

,DATA,Indicador,qte,FX_ATRASO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN
0,2025-09-01,Contrato,581,Preventivo,Set,1,Q3,9,50512.78
1,2025-09-01,Contrato,40601,0-30,Set,1,Q3,9,3135502.72
2,2025-09-01,Contrato,10819,31-60,Set,1,Q3,9,1340927.57
3,2025-09-01,Contrato,8509,61-90,Set,1,Q3,9,3146481.07
4,2025-09-01,Contrato,11303,91-120,Set,1,Q3,9,2215427.82
...,...,...,...,...,...,...,...,...,...
655,2025-09-28,CPF,280214,Unique,Set,20,Q3,9,78559478.39
656,2025-09-29,Contrato,282080,Unique,Set,21,Q3,9,79189838.65
657,2025-09-29,CPF,280354,Unique,Set,21,Q3,9,78562823.95
658,2025-09-30,Contrato,283160,Unique,Set,22,Q3,9,79716266.00
659,2025-09-30,CPF,281431,Unique,Set,22,Q3,9,79086902.24

In [9]:
from src.utils import acionamentos_funil
df_acionamentos_funil, df_analitico_acionamentos_humano, df_acion_semFaixa_humano, df_acion_semDescricao_humano, df_acion_semOrigem_humano, df_analitico_trestto, df_enriquecido_discagens_trestto_semFaixa, df_analitico_expert, df_enriquecido_discagens_expert_semFaixa, df_humano_tabulados_como_robo, df_dicagens_operacaoOutros, df_acionamentos_funil_long = acionamentos_funil(df_tab_acionamentos, df_tabulacao_aciona, df_dw_calendario, df_maling_hist, df_discagens_trestto, df_discagens_expert)

df_acionamentos_funil

✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 720
✓ Total de colunas: 17
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 1,560
✓ Total de colunas: 17
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 750
✓ Total de colunas: 17
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 3,030
✓ Total de colunas: 17
============================================================

,DATA,FX_ATRASO,ORIGEM,TRABALHADO,VALORPRIN_FIN_TRABALHADO,ACIONAMENTOS,VALORPRIN_FIN_ACIONAMENTOS,CPC,VALORPRIN_FIN_CPC,CPCA,VALORPRIN_FIN_CPCA,PROMESSA,VALORPRIN_FIN_PROMESSA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2025-09-01,Preventivo,HUMANO,0.0,0.00,2.0,260.58,2.0,260.58,0.0,0.00,0.0,0.00,1,Q3,9,Set
1,2025-09-01,0-30,HUMANO,0.0,0.00,32.0,1885.71,17.0,951.23,9.0,504.66,4.0,272.63,1,Q3,9,Set
2,2025-09-01,31-60,HUMANO,0.0,0.00,4.0,117.18,2.0,114.86,1.0,56.26,0.0,0.00,1,Q3,9,Set
3,2025-09-01,61-90,HUMANO,0.0,0.00,2.0,3835.80,0.0,0.00,0.0,0.00,0.0,0.00,1,Q3,9,Set
4,2025-09-01,91-120,HUMANO,0.0,0.00,9.0,18682.87,1.0,59.80,1.0,59.80,0.0,0.00,1,Q3,9,Set
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3025,2025-09-30,121-150,Robô,20515.0,3811324.51,3454.0,581073.98,552.0,81764.42,524.0,78221.90,173.0,17804.59,22,Q3,9,Set
3026,2025-09-30,151-180,Robô,13287.0,3596243.00,1884.0,496000.87,289.0,70141.79,271.0,66844.57,81.0,11995.04,22,Q3,9,Set
3027,2025-09-30,181-360,Robô,903.0,282449.40,90.0,23211.46,11.0,2323.06,11.0,2323.06,2.0,263.82,22,Q3,9,Set
3028,2025-09-30,361-720,Robô,182.0,81472.10,14.0,5462.24,6.0,2468.01,6.0,2468.01,0.0,0.00,22,Q3,9,Set
3029,2025-09-30,Maior 720,Robô,51.0,19394.93,8.0,2510.41,2.0,1191.53,2.0,1191.53,0.0,0.00,22,Q3,9,Set

In [23]:
from src.data_wrangling_acionamentos import transformar_funil_formato_long

df_acionamentos_funil_long = transformar_funil_formato_long(df_acionamentos_funil)
df_acionamentos_funil_long

,DATA,Indicador,qte,FX_ATRASO,ORIGEM,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN
0,2025-09-01,acionamentos,32.0,0-30,HUMANO,Set,1,Q3,9,1885.71
1,2025-09-01,acionamentos,0.0,0-30,Humano,Set,1,Q3,9,0.00
2,2025-09-01,acionamentos,1399.0,0-30,Robô,Set,1,Q3,9,131735.05
3,2025-09-01,acionamentos,2842.0,0-30,Robô,Set,1,Q3,9,187380.99
4,2025-09-01,cpc,17.0,0-30,HUMANO,Set,1,Q3,9,951.23
...,...,...,...,...,...,...,...,...,...,...
15145,2025-09-30,trabalhado,16046.0,Unique,Robô,Set,22,Q3,9,2821619.40
15146,2025-09-30,trabalhado,12586.0,Unique,Robô,Set,22,Q3,9,3408711.89
15147,2025-09-30,trabalhado,112.0,Unique,Robô,Set,22,Q3,9,27367.83
15148,2025-09-30,trabalhado,150.0,Unique,Robô,Set,22,Q3,9,70120.88
15149,2025-09-30,trabalhado,47.0,Unique,Robô,Set,22,Q3,9,18788.62

In [32]:
from src.data_wrangling_pagamentos import data_pagamentos, tratar_pagamentos
df_pagamentos_funil, df_sem_fx_atraso, df_pagamento_analitico = tratar_pagamentos(df_pagamentos, df_acordos, df_maling_hist, df_dw_calendario)
df_pagamentos_funil

,DATA_PAGTO,Indicador,qte,FX_ATRASO,TIPO,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR_PARC
2,2025-09-02,Pagamentos,5,0-30,HUMANO,Set,2,Q3,9,358.27
3,2025-09-02,Pagamentos,17,0-30,ROBÔ,Set,2,Q3,9,1058.48
9,2025-09-02,Pagamentos,2,91-120,ROBÔ,Set,2,Q3,9,147.75
10,2025-09-02,Pagamentos,1,121-150,HUMANO,Set,2,Q3,9,161.65
22,2025-09-03,Pagamentos,17,0-30,HUMANO,Set,3,Q3,9,1053.93
...,...,...,...,...,...,...,...,...,...,...
412,2025-09-30,Pagamentos,7,151-180,HUMANO,Set,22,Q3,9,375.82
413,2025-09-30,Pagamentos,4,151-180,ROBÔ,Set,22,Q3,9,679.11
414,2025-09-30,Pagamentos,34,181-360,HUMANO,Set,22,Q3,9,2881.72
416,2025-09-30,Pagamentos,24,361-720,HUMANO,Set,22,Q3,9,2296.49
418,2025-09-30,Pagamentos,1,Maior 720,HUMANO,Set,22,Q3,9,38.96

In [35]:
from src.utils import consolidar_dataframes
df_funil_final = consolidar_dataframes(df_mailing_acumulado, df_pagamentos_funil, df_acionamentos_funil_long)
df_funil_final

,DATA,Indicador,qte,FX_ATRASO,TIPO_ORIGEM,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR
0,2025-09-01,Contrato,581.0,Preventivo,,Set,1,Q3,9,50512.78
1,2025-09-01,Contrato,40601.0,0-30,,Set,1,Q3,9,3135502.72
2,2025-09-01,Contrato,10819.0,31-60,,Set,1,Q3,9,1340927.57
3,2025-09-01,Contrato,8509.0,61-90,,Set,1,Q3,9,3146481.07
4,2025-09-01,Contrato,11303.0,91-120,,Set,1,Q3,9,2215427.82
...,...,...,...,...,...,...,...,...,...,...
16076,2025-09-30,trabalhado,16046.0,Unique,Robô,Set,22,Q3,9,2821619.40
16077,2025-09-30,trabalhado,12586.0,Unique,Robô,Set,22,Q3,9,3408711.89
16078,2025-09-30,trabalhado,112.0,Unique,Robô,Set,22,Q3,9,27367.83
16079,2025-09-30,trabalhado,150.0,Unique,Robô,Set,22,Q3,9,70120.88
16080,2025-09-30,trabalhado,47.0,Unique,Robô,Set,22,Q3,9,18788.62

In [9]:
# INTERSEÇÃO DE CPFS DISCADOS COM E SEM FAIXA DE ATRASO

from src.data_wrangling_discagens_trestto import tratar_discagens_trestto, enriquecer_discagens_trestto, acionamentos_esforco_trestto, interseção_cpfs_discados_trestto

mesagem_resultado = interseção_cpfs_discados_trestto(df_enriquecido_discagens_trestto_limpo, df_enriquecido_discagens_trestto_semFaixa)
mesagem_resultado

📦 CPFs únicos COM FX_ATRASO: 117,039
📦 CPFs únicos SEM FX_ATRASO: 202,507
--------------------------------------------------
📊 Resultados da Comparação de CPFs Únicos

CPFs em AMBOS os grupos (Intersecção): 21,144
-------------------------
CPFs SOMENTE no grupo COM FX_ATRASO: 95,895
CPFs SOMENTE no grupo SEM FX_ATRASO: 181,363

In [34]:
from src import data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert, data_wrangling_pagamentos, utils
import importlib
import queries
importlib.reload(utils)
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(data_wrangling_pagamentos)
importlib.reload(queries)