In [1]:
%load_ext autoreload
%autoreload 2

# import sys 
# sys.path.append("..") 
import sys
sys.path.append(r"C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects")

In [29]:
import importlib 
#from utils import queries
#from utils.mailing import pipelines, metricas_acumuladas, data_processing
#from Renner.src.mailing import metricas_acumuladas, data_processing
#from utils.acionamentos import metricas_acumuladas
from utils.discagens.expert import pipelines, data_processing, metricas_acumuladas
#from utils.acionamentos import pipelines, metricas_acumuladas
#from utils.pagamentos import pipelines, metricas_acumuladas, data_processing
from utils import utils
#from Renner.src.discagens.olos import data_processing
#from utils.digital_channels import data_processing, metricas_acumuladas
from Renner.src import config, data_loader
#from Renner.src.mailing import data_processing, as
#from Renner.utils import queries

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
#importlib.reload(pipelines)
importlib.reload(utils)
importlib.reload(metricas_acumuladas)
importlib.reload(data_processing)
importlib.reload(data_loader)
#importlib.reload(queries)
importlib.reload(config)

In [12]:
import sys
import importlib

# 1. Removemos a referência do módulo da memória
if 'utils.discagens.expert.data_processing' in sys.modules:
    del sys.modules['utils.discagens.expert.data_processing']

# 2. Agora importamos novamente (ele será obrigado a ler do arquivo salvo)
import utils.discagens.expert.data_processing as data_processing

# 3. Teste se a função agora existe lá dentro
if hasattr(data_processing, 'aplicar_transformacoes_discagens'):
    print("Sucesso! A função foi encontrada.")
    # Se quiser trazer para o escopo global:
    from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens
else:
    print("Erro: A função ainda não foi detectada no arquivo. Verifique se salvou o arquivo .py")

Sucesso! A função foi encontrada.

In [ ]:
import importlib
import Ouze.src.config as config

importlib.reload(config)

GRUPO_PRINCIPAL_MAP = config.GRUPO_PRINCIPAL_MAP
TRANSFORMACOES_DISCAGENS = config.TRANSFORMACOES_DISCAGENS
DIMENSOES_PAGAMENTOS = config.DIMENSOES_PAGAMENTOS
OUZE_PATHS = config.OUZE_PATHS
CAMINHO_BASE_OUZE = config.CAMINHO_BASE_OUZE

In [73]:
import pandas as pd
from utils.db_connection import get_db_connections
from Renner.utils.queries import get_query_base_aux_renner

# 1️⃣ Gera a query
query = get_query_base_aux_renner(
)

# 2️⃣ Abre conexão e executa
with get_db_connections() as (conn_trc, conn_bd2, conn_src):
    df_base_auxiliar_renner = pd.read_sql(query, conn_src)

df_base_auxiliar_renner

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_4844\2368934097.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_base_auxiliar_renner = pd.read_sql(query, conn_src)

🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

        CONTRATO_FIN CONTRATO_ORIGINAL PRODUTO
0         49471715ID       00000000047     CDC
1         40959171ID       00000000490     CDC
2         53923191ID       00000000492     CDC
3         53264525ID       00000000613     CDC
4         51585917ID       00000001036     CDC
...              ...               ...     ...
2326740   45482997ID     4589107054014     CDC
2326741   40560138ID     4799076641665     CDC
2326742   53554395ID     5179137341235     CDC
2326743   52446270ID     5339138205291     CDC
2326744   48225674ID   5619112587387_2   RENEG

[2326745 rows x 3 columns]

In [3]:
# sobe para Projects 
from Renner.src.data_loader import load_data_renner

dados = load_data_renner('2026-01-01', '2026-01-31')

(
df_discagens_expert, 
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_whats,
df_base_auxiliar_renner,
df_discagens_olos
) = dados.values()

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:484: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/11] ✓ Discagens Expert: 1.339.446 registros (4m 31s)
[2/11] ✓ Mailing Histórico: 4.959.815 registros (2m 43s)
[3/11] ✓ Tabulação de Acionamentos: 176.098 registros (34s)
[4/11] ✓ Tabulação Acionamentos: 9.794 registros (0s)
[5/11] ✓ Calendário: 21 registros (0s)
[6/11] ✓ Pagamentos: 18.357 registros (3s)
[7/11] ✓ Acordos: 2.955 registros (2s)
[8/11] ✓ SMS: 98.593 registros (1s)
[9/11] ✓ RCS: 100.420 registros (1s)
[10/11] ✓ Email: 1.135.078 registros (6s)
[11/11] ✓ WhatsApp: 63.233 registros (0s)

✅ Carregamento concluído em 8m 6s
🔍 Carregando base_auxiliar_renner (Renner)...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Renner\src\data_loader.py:72: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dados[dataset] = pd.read_sql(query_sql, conn_src)

✅ base_auxiliar_renner carregado — 2,350,324 linhas
🔍 Carregando discagens_olos (Renner)...
✅ discagens_olos carregado — 3,739,953 linhas
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [5]:
from utils.mailing.pipelines import processar_mailing_completo
from Renner.src.mailing.data_processing import merge_mailing_com_base_aux, add_faixa
from Renner.src.mailing.metricas_acumuladas import gerar_acumulado_mailing_unique_por_faixa
from functools import partial
from Renner.src.config import FAIXAS_ATRASO_BINS, FAIXAS_ATRASO_LABELS

df_tratado, df_final = processar_mailing_completo(
    df_mailing_hist,
    df_dw_calendario,
    bins=FAIXAS_ATRASO_BINS,
    labels=FAIXAS_ATRASO_LABELS,
    tratamentos_extras=[
        partial(merge_mailing_com_base_aux, df_base_auxiliar_renner=df_base_auxiliar_renner),
        add_faixa
    ],
    segmentacoes_extras=['FAIXA'],
    acumulados_extras=[
        partial(gerar_acumulado_mailing_unique_por_faixa, segmentacoes_extras=['FAIXA'])
    ]
)

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 3,570
✓ Total de colunas: 10
============================================================

In [53]:
#df_mailing_hist
#df_base_auxiliar_renner
#df_tratado
#df_final
#df_tratado['FAIXA'].value_counts()
# df_r1_r2 = df_tratado[df_tratado['FAIXA'].isin(['R1', 'R2'])]
# df_r1_r2
# df_filtrado = df_tratado[
#     (df_tratado['PRODUTO'] == 'RENEG') &
#     (df_tratado['ATRASO'].between(11, 180))
# ]
#df_filtrado
#df_discagens_expert

#df_discagens_olos
print(df_discagens_tratado.columns)
#df_discagens_tratado
#df_tab_acionamentos
#df_discagens_tratado['GrupoPrincipal'].unique()
#df_discagens_tratado['ResultadoClassificacao'].unique()
df_discagens_tratado['Instante200OKPub'].unique()

Index(['DATA', 'id', 'CONTRATO', 'ddd', 'fone', 'GrupoPrincipal',
       'UltCodSigRecPublica', 'ResultadoClassificacao',
       'MotivoEncerramentoBilhete', 'Instante200OKPub', 'Agente',
       'tempoconversacao_ms', 'codtabulacao', 'OPERACAO', 'ESTADO', 'ATRASO',
       'COD_CLI', 'COD_CAR', 'VALOR', 'FX_ATRASO', 'CONTRATO_ORIGINAL',
       'PRODUTO', 'FAIXA', 'CPF', 'nr_dia_util', 'quartil', 'dt_mes',
       'mes_abreviado', 'TRABALHADO', 'ACIONAMENTOS', 'CPC', 'CPCA',
       'PROMESSA'],
      dtype='object')

<DatetimeArray>
['1899-12-30 00:00:00', '2026-01-05 09:32:20', '2026-01-05 09:33:24',
 '2026-01-05 09:33:59', '2026-01-05 09:37:06', '2026-01-05 09:37:08',
 '2026-01-05 09:38:15', '2026-01-05 09:38:17', '2026-01-05 09:38:51',
 '2026-01-05 09:40:31',
 ...
 '2026-01-31 13:10:32', '2026-01-31 13:10:42', '2026-01-31 13:10:48',
 '2026-01-31 13:10:56', '2026-01-31 13:10:54', '2026-01-31 13:11:08',
 '2026-01-31 13:11:10', '2026-01-31 13:11:17', '2026-01-31 13:11:40',
 '2026-01-31 13:11:45']
Length: 430683, dtype: datetime64[ns]

In [33]:
from Renner.src.config import TRANSFORMACOES_DISCAGENS
from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens

df_discagens_tratado, df_sem_fx_atraso = aplicar_transformacoes_discagens(
    df=df_discagens_expert,
    config=TRANSFORMACOES_DISCAGENS,
    df_mailing=df_tratado,
    df_calendario=df_dw_calendario,
)
df_discagens_tratado

,DATA,id,CONTRATO,ddd,fone,GrupoPrincipal,UltCodSigRecPublica,ResultadoClassificacao,MotivoEncerramentoBilhete,Instante200OKPub,...,CPF,nr_dia_util,quartil,dt_mes,mes_abreviado,TRABALHADO,ACIONAMENTOS,CPC,CPCA,PROMESSA
0,2026-01-05,260,55402680ID,61,996330222,4527,480,,foneforadeservico,1899-12-30 00:00:00,...,2778209107,2.0,Q1,1.0,Jan,1,0,0,0,0
1,2026-01-05,574,55411276ID,15,998001085,4527,200,,desligamentorecebidocliente,2026-01-05 09:32:20,...,45474111827,2.0,Q1,1.0,Jan,1,0,0,0,0
2,2026-01-05,2569,51064793ID,16,988388727,4527,200,cxpre,bloqueiodetector,2026-01-05 09:33:24,...,8390047616,2.0,Q1,1.0,Jan,1,0,0,0,0
3,2026-01-05,2618,41711078ID,19,992615818,4527,480,cxpre,bloqueiodetector,1899-12-30 00:00:00,...,29615694860,2.0,Q1,1.0,Jan,1,0,0,0,0
4,2026-01-05,3310,54548155ID,41,988028338,4527,480,,foneforadeservico,1899-12-30 00:00:00,...,62450129375,2.0,Q1,1.0,Jan,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339438,2026-01-31,51427684,52356569ID,11,965783059,4522,408,,naoatende,1899-12-30 00:00:00,...,22886343838,NaN,NaN,NaN,NaN,1,0,0,0,0
1339439,2026-01-31,51427845,40960239ID,19,993136220,4522,200,cxpos,bloqueiodetector,2026-01-31 13:11:45,...,46097733844,NaN,NaN,NaN,NaN,1,0,0,0,0
1339440,2026-01-31,51428154,50968650ID,11,914038605,4522,,cxpre,bloqueiodetector,1899-12-30 00:00:00,...,49921846850,NaN,NaN,NaN,NaN,1,0,0,0,0
1339441,2026-01-31,51428812,47242615ID,31,998598008,4522,408,,naoatende,1899-12-30 00:00:00,...,1518395651,NaN,NaN,NaN,NaN,1,0,0,0,0
1339442,2026-01-31,51429067,43832295ID,55,999364241,4522,408,,naoatende,1899-12-30 00:00:00,...,7766348950,NaN,NaN,NaN,NaN,1,0,0,0,0

In [55]:
import pandas as pd
df_discagens_tratado['DATA'] = pd.to_datetime(df_discagens_tratado['DATA'])
df_sabado = df_discagens_tratado[
    df_discagens_tratado['DATA'].dt.weekday == 5
]
df_sabado

,DATA,id,CONTRATO,ddd,fone,GrupoPrincipal,UltCodSigRecPublica,ResultadoClassificacao,MotivoEncerramentoBilhete,Instante200OKPub,...,CPF,nr_dia_util,quartil,dt_mes,mes_abreviado,TRABALHADO,ACIONAMENTOS,CPC,CPCA,PROMESSA
93852,2026-01-10,11588212,55589248ID,19,988275291,4527,404,,foneinexistente,1899-12-30 00:00:00,...,52006811894,NaN,NaN,NaN,NaN,1,0,0,0,0
93853,2026-01-10,11588217,53260509ID,13,997556530,4527,480,,foneforadeservico,1899-12-30 00:00:00,...,31009993801,NaN,NaN,NaN,NaN,1,0,0,0,0
93854,2026-01-10,11588233,55507105ID,11,957234012,4527,200,cxpos,bloqueiodetector,2026-01-10 08:00:12,...,46350937864,NaN,NaN,NaN,NaN,1,0,0,0,0
93855,2026-01-10,11588246,55346897ID,17,997882702,4527,200,cxpre,bloqueiodetector,2026-01-10 08:00:11,...,42582391867,NaN,NaN,NaN,NaN,1,0,0,0,0
93856,2026-01-10,11588252,55324333ID,11,941891113,4527,200,cxpos,bloqueiodetector,2026-01-10 08:00:09,...,47848437876,NaN,NaN,NaN,NaN,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1339438,2026-01-31,51427684,52356569ID,11,965783059,4522,408,,naoatende,1899-12-30 00:00:00,...,22886343838,NaN,NaN,NaN,NaN,1,0,0,0,0
1339439,2026-01-31,51427845,40960239ID,19,993136220,4522,200,cxpos,bloqueiodetector,2026-01-31 13:11:45,...,46097733844,NaN,NaN,NaN,NaN,1,0,0,0,0
1339440,2026-01-31,51428154,50968650ID,11,914038605,4522,,cxpre,bloqueiodetector,1899-12-30 00:00:00,...,49921846850,NaN,NaN,NaN,NaN,1,0,0,0,0
1339441,2026-01-31,51428812,47242615ID,31,998598008,4522,408,,naoatende,1899-12-30 00:00:00,...,1518395651,NaN,NaN,NaN,NaN,1,0,0,0,0
1339442,2026-01-31,51429067,43832295ID,55,999364241,4522,408,,naoatende,1899-12-30 00:00:00,...,7766348950,NaN,NaN,NaN,NaN,1,0,0,0,0

In [13]:
from Renner.src.discagens.olos.data_processing import enriquecer_olos_com_mailing_calendario, processar_trabalhado, processar_massivos
import pandas as pd

df_discagens, df_massivos_com_mailing = processar_trabalhado(
    df_expert=df_discagens_tratado,
    df_olos=df_discagens_olos,
    df_sms=df_sms,
    df_rcs=df_rcs,
    df_email=df_email,
    df_whats=df_whats,
    df_mailing_hist=df_tratado,
    df_dw_calendario=df_dw_calendario
)
df_discagens

Massivos unificados: 1,397,324 registros

,DATA,CONTRATO,CPF,GrupoPrincipal,CANAL,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO,...,MotivoEncerramentoBilhete,Instante200OKPub,Agente,tempoconversacao_ms,codtabulacao,TRABALHADO,ACIONAMENTOS,CPC,CPCA,PROMESSA
0,2026-01-05,55402680ID,2778209107,4527.0,EXPERT,553.0,247.0,3.0,190.88,7 - 361-720,...,foneforadeservico,1899-12-30 00:00:00,,0.0,None,1.0,0.0,0.0,0.0,0.0
1,2026-01-05,55411276ID,45474111827,4527.0,EXPERT,800.0,247.0,3.0,184.37,8 - 721-1440,...,desligamentorecebidocliente,2026-01-05 09:32:20,,0.0,None,1.0,0.0,0.0,0.0,0.0
2,2026-01-05,51064793ID,8390047616,4527.0,EXPERT,174.0,247.0,3.0,180.54,5 - 151-180,...,bloqueiodetector,2026-01-05 09:33:24,,0.0,None,1.0,0.0,0.0,0.0,0.0
3,2026-01-05,41711078ID,29615694860,4527.0,EXPERT,918.0,247.0,3.0,268.11,8 - 721-1440,...,bloqueiodetector,1899-12-30 00:00:00,,0.0,None,1.0,0.0,0.0,0.0,0.0
4,2026-01-05,54548155ID,62450129375,4527.0,EXPERT,151.0,247.0,3.0,179.84,5 - 151-180,...,foneforadeservico,1899-12-30 00:00:00,,0.0,None,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6405315,2026-01-27,47340555ID,84418796215,NaN,WHATS,506.0,247.0,3.0,7135.42,7 - 361-720,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6405316,2026-01-27,51618558ID,8993318905,NaN,WHATS,506.0,247.0,3.0,5355.35,7 - 361-720,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6405317,2026-01-27,48822870ID,11859668895,NaN,WHATS,506.0,247.0,3.0,5117.80,7 - 361-720,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6405318,2026-01-27,49607493ID,10751147800,NaN,WHATS,507.0,247.0,3.0,10388.62,7 - 361-720,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6405319,2026-01-27,47389171ID,1390763790,NaN,WHATS,509.0,247.0,3.0,12806.15,7 - 361-720,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Contratos únicos da OLOS
contratos_olos = set(df_discagens_olos['CONTRATO'].astype(str).str.upper().str.strip().unique())
print(f"Contratos únicos OLOS: {len(contratos_olos):,}")

# Nova base mailing filtrada pelos contratos da OLOS
df_mailing_olos = df_tratado[df_tratado['CONTRATO'].astype(str).str.upper().str.strip().isin(contratos_olos)].reset_index(drop=True)
print(f"Mailing filtrado: {len(df_mailing_olos):,}")

Contratos únicos OLOS: 73,273
Mailing filtrado: 1,495,473

In [ ]:
from utils.discagens.expert.metricas_acumuladas import processar_acumulados_discagens, discagens_unique_daily, discagens_esforco_daily, discagens_fxAtraso_daily, processar_acumulados_discagens_completo, processar_acumulados_discagens_operacao

df_discagens_final = processar_acumulados_discagens_completo(
    df_discagens=df_discagens_tratado,
    df_dw_calendario=df_dw_calendario,
    segmentacoes_extras=['FAIXA'],
    retorno='consolidado'
)
# df_discagens_final = processar_acumulados_discagens(
#     df_discagens=df_discagens,
#     df_dw_calendario=df_dw_calendario,
#     segmentacoes_extras=['FAIXA'],
#     retorno='consolidado'
# )
# df_discagens_final = processar_acumulados_discagens_operacao(
#     df_discagens=df_discagens_tratado,
#     #df_dw_calendario=df_dw_calendario,
#     segmentacoes_extras=['FAIXA'],
#     retorno='consolidado'
# )
df_discagens_final

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 4,641
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 2,988
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 7,629
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,FX_ATRASO,FAIXA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-05,URA,0,Preventivo,C1,Jan,2.0,Q1,1.0,0.000000e+00,Funil
1,2026-01-05,URA,0,Preventivo,C2,Jan,2.0,Q1,1.0,0.000000e+00,Funil
2,2026-01-05,URA,0,Preventivo,OUTROS,Jan,2.0,Q1,1.0,0.000000e+00,Funil
3,2026-01-05,URA,0,Preventivo,PRE_WO,Jan,2.0,Q1,1.0,0.000000e+00,Funil
4,2026-01-05,URA,0,Preventivo,R1,Jan,2.0,Q1,1.0,0.000000e+00,Funil
...,...,...,...,...,...,...,...,...,...,...,...
7624,2026-01-29,ATIVO,21109,Esforço,Esforço,Jan,20.0,Q1,1.0,1.010933e+08,Daily
7625,2026-01-29,URA,48262,Esforço,Esforço,Jan,20.0,Q1,1.0,4.377039e+07,Daily
7626,2026-01-30,ATIVO,23491,Esforço,Esforço,Jan,21.0,Q1,1.0,3.937616e+07,Daily
7627,2026-01-30,URA,60009,Esforço,Esforço,Jan,21.0,Q1,1.0,5.204526e+07,Daily
7628,2026-01-31,ATIVO,13226,Esforço,Esforço,N/A,0.0,0,0.0,1.274707e+07,Daily

In [9]:
from Renner.src.discagens.olos.data_processing import enriquecer_olos_com_mailing_calendario, preparar_massivos, processar_trabalhado, processar_massivos, unir_discagens_expert_olos

df_olos_com_fx, _ = enriquecer_olos_com_mailing_calendario(
    df_olos=df_discagens_olos,
    df_mailing_hist=df_tratado,
    df_dw_calendario=df_dw_calendario
)

df_expert_olos = unir_discagens_expert_olos(
        df_expert=df_discagens_tratado,
        df_olos=df_olos_com_fx
    )
df_expert_olos

,DATA,CONTRATO,CPF,GrupoPrincipal,CANAL,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO,...,MotivoEncerramentoBilhete,Instante200OKPub,Agente,tempoconversacao_ms,codtabulacao,TRABALHADO,ACIONAMENTOS,CPC,CPCA,PROMESSA
0,2026-01-05,55402680ID,2778209107,4527,EXPERT,553.0,247.0,3.0,190.88,7 - 361-720,...,foneforadeservico,1899-12-30 00:00:00,,0.0,None,1.0,0.0,0.0,0.0,0.0
1,2026-01-05,55411276ID,45474111827,4527,EXPERT,800.0,247.0,3.0,184.37,8 - 721-1440,...,desligamentorecebidocliente,2026-01-05 09:32:20,,0.0,None,1.0,0.0,0.0,0.0,0.0
2,2026-01-05,51064793ID,8390047616,4527,EXPERT,174.0,247.0,3.0,180.54,5 - 151-180,...,bloqueiodetector,2026-01-05 09:33:24,,0.0,None,1.0,0.0,0.0,0.0,0.0
3,2026-01-05,41711078ID,29615694860,4527,EXPERT,918.0,247.0,3.0,268.11,8 - 721-1440,...,bloqueiodetector,1899-12-30 00:00:00,,0.0,None,1.0,0.0,0.0,0.0,0.0
4,2026-01-05,54548155ID,62450129375,4527,EXPERT,151.0,247.0,3.0,179.84,5 - 151-180,...,foneforadeservico,1899-12-30 00:00:00,,0.0,None,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5043022,2026-01-05,55435013ID,12772779823,16,OLOS,87.0,247.0,3.0,2531.62,2 - 61-90,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5043023,2026-01-05,54541620ID,7235331488,16,OLOS,174.0,247.0,3.0,2529.28,5 - 151-180,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5043024,2026-01-05,54537105ID,77832582553,16,OLOS,175.0,247.0,3.0,3233.25,5 - 151-180,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5043025,2026-01-05,51685031ID,36923518873,14,OLOS,329.0,247.0,3.0,3574.40,6 - 181-360,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5043026,2026-01-05,52265401ID,621302180,14,OLOS,245.0,247.0,3.0,6896.92,6 - 181-360,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
from Renner.src.discagens.olos.data_processing import enriquecer_olos_com_mailing_calendario, preparar_massivos, processar_trabalhado, processar_massivos

df_massivos_com_mailing, _ = processar_massivos(
    df_sms=df_sms,
    df_rcs=df_rcs,
    df_email=df_email,
    df_whats=df_whats,
    df_discagens=df_expert_olos,
    df_mailing_hist=df_tratado,
    df_dw_calendario=df_dw_calendario
)
df_massivos_com_mailing

Massivos unificados: 1,397,324 registros

,CPF,DATA,CANAL,CONTRATO,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO,CONTRATO_ORIGINAL,PRODUTO,FAIXA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2400130507,2026-01-05,SMS,55530119ID,133.0,247.0,3.0,4580.59,4 - 121-150,00008494384,CDC,C1,2,Q1,1,Jan
1,43386909841,2026-01-05,SMS,55529935ID,133.0,247.0,3.0,6320.13,4 - 121-150,00006490545,CDC,C1,2,Q1,1,Jan
2,50683094866,2026-01-05,SMS,55534787ID,132.0,247.0,3.0,74.88,4 - 121-150,21000642576078,CDC,C1,2,Q1,1,Jan
3,18056897895,2026-01-05,SMS,55534317ID,92.0,247.0,3.0,3260.42,3 - 91-120,00011706735,CDC,C1,2,Q1,1,Jan
4,40209473843,2026-01-05,SMS,55534406ID,92.0,247.0,3.0,5482.38,3 - 91-120,00012533879,CDC,C1,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547071,53510429168,2026-01-28,WHATS,44029398ID,713.0,247.0,3.0,3505.80,7 - 361-720,00009017513,CDC,WO,19,Q1,1,Jan
547072,53529891860,2026-01-28,WHATS,40468654ID,1269.0,247.0,3.0,2038.67,8 - 721-1440,00008339902,CDC,WO,19,Q1,1,Jan
547073,53549694253,2026-01-28,WHATS,40714934ID,1068.0,247.0,3.0,1103.44,8 - 721-1440,00009021611_1,RENEG,WO,19,Q1,1,Jan
547074,53549694253,2026-01-28,WHATS,40714934ID,1068.0,247.0,3.0,1103.44,8 - 721-1440,00009021611_1,RENEG,WO,19,Q1,1,Jan
547075,53549694253,2026-01-28,WHATS,40714934ID,1068.0,247.0,3.0,1103.44,8 - 721-1440,00009021611_1,RENEG,WO,19,Q1,1,Jan

In [24]:
from utils.digital_channels.metricas_acumuladas import processar_acumulados_massivos

# Retorno consolidado com coluna TIPO
df_tudo = processar_acumulados_massivos(
    df_massivos=df_massivos_com_mailing,
    segmentacoes_extras=['FAIXA'],
    retorno='consolidado'
)
df_tudo

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 5,532
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 3,521
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 9,053
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,FX_ATRASO,FAIXA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN,TIPO
0,2026-01-05,EMAIL,0,Preventivo,C1,Jan,2,Q1,1,0.00,Funil
1,2026-01-05,EMAIL,0,Preventivo,C2,Jan,2,Q1,1,0.00,Funil
2,2026-01-05,EMAIL,0,Preventivo,PRE_WO,Jan,2,Q1,1,0.00,Funil
3,2026-01-05,EMAIL,0,Preventivo,R1,Jan,2,Q1,1,0.00,Funil
4,2026-01-05,EMAIL,0,Preventivo,R2,Jan,2,Q1,1,0.00,Funil
...,...,...,...,...,...,...,...,...,...,...,...
9048,2026-01-28,RCS,1619,Esforço,Esforço,Jan,19,Q1,1,2487581.45,Daily
9049,2026-01-28,WHATS,7730,Esforço,Esforço,Jan,19,Q1,1,35982527.95,Daily
9050,2026-01-29,EMAIL,30742,Esforço,Esforço,Jan,20,Q1,1,86706708.60,Daily
9051,2026-01-29,RCS,5572,Esforço,Esforço,Jan,20,Q1,1,31369388.31,Daily
9052,2026-01-30,SMS,6990,Esforço,Esforço,Jan,21,Q1,1,16336912.12,Daily

In [6]:
df_tab_acionamentos
df_tabulacao_aciona

from utils.acionamentos.data_processing import confere_tabulacao_acionamentos, enriquecer_acionamentos

df_acionamentos_tratado = confere_tabulacao_acionamentos(
    df_tab_acionamentos=df_tab_acionamentos,
    df_tabulacao_aciona=df_tabulacao_aciona
)
df_acionamentos_limpo, df_acionamentos_sem_fx, df_acionamentos_sem_descricao = enriquecer_acionamentos(
    df_acionamentos=df_acionamentos_tratado,
    df_mailing_hist=df_tratado,
    df_dw_calendario=df_dw_calendario
)
df_acionamentos_limpo

,DATA_ACIONA,HORA,CONTRATO_FIN,CPF_DEV,COD_ACIONA,DESC_ACIONAMENTO,COD_RECUP,NOME_RECUP,LOGIN_RECUP,ULTGRUPO_RECUP,...,VALOR,FX_ATRASO,CONTRATO_ORIGINAL,PRODUTO,FAIXA,COD_CLI,nr_dia_util,quartil,dt_mes,mes_abreviado
6202,2026-01-02,09:31:50.186666,43863657ID,9050041752,11246,CONTATO COM TERCEIROS-OLOS,19090,LUCAS VIDAL MAIA,LUCAS_RN,RENNER,...,9694.63,8 - 721-1440,00001666745,CDC,WO,247.0,1.0,Q1,1.0,Jan
6203,2026-01-02,09:33:35.720000,43863657ID,9050041752,11248,DESCONHECE CLIENTE - ENGANO-OLOS,19090,LUCAS VIDAL MAIA,LUCAS_RN,RENNER,...,9694.63,8 - 721-1440,00001666745,CDC,WO,247.0,1.0,Q1,1.0,Jan
6204,2026-01-02,08:52:52.006666,50490051ID,4260027760,11246,CONTATO COM TERCEIROS-OLOS,18394,NERIANE CRISTINA GARCIA,NERIANEG_RN,RENNER - OLOS,...,4445.22,8 - 721-1440,00009933562,CDC,WO,247.0,1.0,Q1,1.0,Jan
6207,2026-01-02,09:23:10.783333,54356173ID,13639653602,11256,LIGACAO SEM INTERACAO - MUDA-OLOS,16769,CRISTIANE SILVA,CRISTIANESI_RN,RENNER - OLOS,...,3600.50,6 - 181-360,00011514391,CDC,C2,247.0,1.0,Q1,1.0,Jan
6208,2026-01-02,11:44:14.370000,54355822ID,34156379809,11248,DESCONHECE CLIENTE - ENGANO-OLOS,17569,MARCELO AUGUSTO CHAVES BARBOSA \t,MARCELO_RN,RENNER,...,8114.34,8 - 721-1440,00004647486,CDC,WO,247.0,1.0,Q1,1.0,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175021,2026-01-16,00:00:00,51589548ID,41536955809,10505,ENVIO DE RCS SUCESSO INCENTIVO,15578,MARCELE CAROLINE SANTOS SARGENTIM,MARCELE.SARGENTIM,TECNOLOGIA,...,5088.52,8 - 721-1440,00009451446_2,RENEG,WO,247.0,11.0,Q1,1.0,Jan
175022,2026-01-29,00:00:00,51589548ID,41536955809,10505,ENVIO DE RCS SUCESSO INCENTIVO,15578,MARCELE CAROLINE SANTOS SARGENTIM,MARCELE.SARGENTIM,TECNOLOGIA,...,5088.52,8 - 721-1440,00009451446_2,RENEG,WO,247.0,20.0,Q1,1.0,Jan
175024,2026-01-15,14:43:08.076666,46617050ID,14310734669,10001,DESCONHECE CLIENTE - ENGANO,18162,ALLAN ANDRADE CABRAL,ALLAN_RN,RENNER - OLOS,...,2527.94,8 - 721-1440,00009284958,CDC,WO,247.0,10.0,Q1,1.0,Jan
175025,2026-01-29,00:00:00,55836722ID,6368361930,10505,ENVIO DE RCS SUCESSO INCENTIVO,15578,MARCELE CAROLINE SANTOS SARGENTIM,MARCELE.SARGENTIM,TECNOLOGIA,...,2393.60,1 - 31-60,00003774804_1,RENEG,R1,247.0,20.0,Q1,1.0,Jan
175026,2026-01-29,00:00:00,55669234ID,34034132841,10505,ENVIO DE RCS SUCESSO INCENTIVO,15578,MARCELE CAROLINE SANTOS SARGENTIM,MARCELE.SARGENTIM,TECNOLOGIA,...,2146.68,7 - 361-720,00006838620,CDC,PRE_WO,247.0,20.0,Q1,1.0,Jan

In [90]:
from utils.acionamentos.metricas_acumuladas import acionamentos_fxAtraso_funil, processar_acumulados_acionamentos, acionamentos_fxAtraso_daily, acionamentos_esforco_daily, acionamentos_unique_daily, acionamentos_unique_funil, acionamentos_esforco_funil
from utils.utils import unir_dataframes

df_acionamentos_final = processar_acumulados_acionamentos(
    df_acionamentos_limpo=df_acionamentos_limpo,
    df_dw_calendario=df_dw_calendario,
    segmentacoes_extras=['FAIXA'],
    retorno='consolidado'
)
df_acionamentos_final

✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 6,636
✓ Total de colunas: 10
============================================================
✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 7,732
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 14,368
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,FX_ATRASO,FAIXA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN,TIPO
0,2026-01-02,Acionamentos,0.0,Preventivo,C1,Jan,1,Q1,1,0.00,Funil
1,2026-01-02,Acionamentos,0.0,Preventivo,C2,Jan,1,Q1,1,0.00,Funil
2,2026-01-02,Acionamentos,0.0,Preventivo,OUTROS,Jan,1,Q1,1,0.00,Funil
3,2026-01-02,Acionamentos,0.0,Preventivo,PRE_WO,Jan,1,Q1,1,0.00,Funil
4,2026-01-02,Acionamentos,0.0,Preventivo,R1,Jan,1,Q1,1,0.00,Funil
...,...,...,...,...,...,...,...,...,...,...,...
14363,2026-01-30,Promessa,185.0,Esforço,Esforço,Jan,21,Q1,1,601172.18,Daily
14364,2026-01-31,Acionamentos,1427.0,Esforço,Esforço,N/A,0,0,0,6826170.02,Daily
14365,2026-01-31,CPC,183.0,Esforço,Esforço,N/A,0,0,0,1023677.26,Daily
14366,2026-01-31,CPCA,170.0,Esforço,Esforço,N/A,0,0,0,976265.86,Daily
14367,2026-01-31,Promessa,91.0,Esforço,Esforço,N/A,0,0,0,442716.47,Daily

In [ ]:
from utils.pagamentos.data_processing import data_pagamentos
from utils.pagamentos.metricas_acumuladas import gerar_acumulado_por_dia_util
from Renner.src.config import DIMENSOES_PAGAMENTOS

#df_acordos
df_pagamentos_tratado, df_pagamentos_sem_fx_atraso, df_pagamentos_analitico = data_pagamentos(
    df_pagamentos=df_pagamentos, 
    df_acordos=df_acordos, 
    df_mailing_hist=df_tratado, 
    df_dw_calendario=df_dw_calendario
)

df_pagamentos_tratado

,DATA_PAGTO,VALOR_PARC,NACORDO_ACO,CONTRATO_FIN,CPF_DEV,COD_CLI_x,VALORPRIN_FIN,VALOR_FIN,STATCONT_FIN,DTDEVOL_FIN,...,mes_abreviado,CPF,ATRASO,COD_CLI_y,COD_CAR,VALOR,FX_ATRASO,CONTRATO_ORIGINAL,PRODUTO,FAIXA
1,2026-01-02,193.28,1,38747440ID,4572399727,247,1128.33,2012.59,1,2026-01-02 00:12:59.040,...,Jan,4572399727,1547.0,247.0,3.0,2012.59,9 - Maior 1440,21000428527256,CDC,WO
2,2026-01-02,193.28,1,38747200ID,4572399727,247,130.70,262.36,1,2026-01-02 00:13:01.213,...,Jan,4572399727,1550.0,247.0,3.0,262.36,9 - Maior 1440,21000427954626,CDC,WO
3,2026-01-02,182.46,1,44482654ID,3878964145,247,52.40,105.18,1,2026-01-02 00:13:10.610,...,Jan,3878964145,1248.0,247.0,3.0,105.18,8 - 721-1440,21000467753563,CDC,WO
4,2026-01-02,182.46,1,44485371ID,3878964145,247,265.00,532.00,1,2026-01-02 00:13:10.613,...,Jan,3878964145,1223.0,247.0,3.0,532.00,8 - 721-1440,21000488923903,CDC,WO
5,2026-01-02,182.46,1,44485333ID,3878964145,247,261.50,524.92,1,2026-01-02 00:13:10.613,...,Jan,3878964145,1226.0,247.0,3.0,524.92,8 - 721-1440,21000488234895,CDC,WO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18349,2026-01-05,63.90,0,49496623ID,7052110610,247,447.30,447.30,0,NaT,...,Jan,7052110610,-36.0,247.0,4.0,639.00,Preventivo,2025040505540169_1,RENEG,OUTROS
18351,2026-01-30,56.25,0,55323834ID,8685655471,247,617.03,617.03,0,NaT,...,Jan,8685655471,-21.0,247.0,4.0,748.09,Preventivo,2024090904990982_2,RENEG,OUTROS
18352,2026-01-26,173.27,0,55589613ID,70270625186,247,693.08,693.08,0,NaT,...,Jan,70270625186,-32.0,247.0,4.0,1039.62,Preventivo,2025111006080382_2,RENEG,OUTROS
18353,2026-01-27,216.36,0,54935135ID,12771680912,247,432.72,432.72,0,NaT,...,Jan,12771680912,-7.0,247.0,4.0,865.44,Preventivo,2025101006011962_2,RENEG,OUTROS
18354,2026-01-30,64.32,0,54955197ID,13220687717,247,385.92,385.92,0,NaT,...,Jan,13220687717,-3.0,247.0,4.0,514.56,Preventivo,2025071705799427_2,RENEG,OUTROS

In [ ]:
from utils.pagamentos.metricas_acumuladas import processar_acumulados_pagamentos

df_pagamentos = processar_acumulados_pagamentos(
    df_pagamentos_tratado=df_pagamentos_analitico,
    df_dw_calendario=df_dw_calendario,
    dimensoes_segmentacao=['FAIXA'],
    retorno='consolidado'
)

df_pagamentos

============================================================
✓ 6 DataFrames unidos com sucesso
✓ Total de linhas: 755
✓ Total de colunas: 10
============================================================

============================================================
✓ 6 DataFrames unidos com sucesso
✓ Total de linhas: 775
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 1,530
✓ Total de colunas: 11
============================================================

,DATA_PAGTO,Indicador,qte,FX_ATRASO,FAIXA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR_PARC,TIPO
0,2026-01-05,Pagamentos,1,3 - 91-120,R1,Jan,2,Q1,1,266.30,Funil
1,2026-01-05,Pagamentos,18,6 - 181-360,C2,Jan,2,Q1,1,8884.62,Funil
2,2026-01-05,Pagamentos,2,6 - 181-360,R2,Jan,2,Q1,1,1434.94,Funil
3,2026-01-05,Pagamentos,1,7 - 361-720,WO,Jan,2,Q1,1,412.10,Funil
4,2026-01-05,Pagamentos,1,8 - 721-1440,WO,Jan,2,Q1,1,159.01,Funil
...,...,...,...,...,...,...,...,...,...,...,...
1525,2026-01-27,Pagamentos,440,Unique,Unique,Jan,18,Q1,1,131778.36,Daily
1526,2026-01-28,Pagamentos,502,Unique,Unique,Jan,19,Q1,1,139126.20,Daily
1527,2026-01-29,Pagamentos,530,Unique,Unique,Jan,20,Q1,1,167174.49,Daily
1528,2026-01-30,Pagamentos,989,Unique,Unique,Jan,21,Q1,1,273400.85,Daily
1529,2026-01-31,Pagamentos,296,Unique,Unique,N/A,0,N/A,0,75658.57,Daily

In [39]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_discagens_final.to_csv('df_discagens_final.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_discagens_final.csv')  # abre com o programa padrão

In [15]:
df_discagens_final

,DATA,Indicador,qte,FX_ATRASO,FAIXA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-02,Trabalhado,0,Preventivo,C1,Jan,1.0,Q1,1.0,0.000000e+00,Funil
1,2026-01-02,Trabalhado,0,Preventivo,C2,Jan,1.0,Q1,1.0,0.000000e+00,Funil
2,2026-01-02,Trabalhado,0,Preventivo,OUTROS,Jan,1.0,Q1,1.0,0.000000e+00,Funil
3,2026-01-02,Trabalhado,0,Preventivo,PRE_WO,Jan,1.0,Q1,1.0,0.000000e+00,Funil
4,2026-01-02,Trabalhado,0,Preventivo,R1,Jan,1.0,Q1,1.0,0.000000e+00,Funil
...,...,...,...,...,...,...,...,...,...,...,...
3686,2026-01-27,Trabalhado,298439,Esforço,Esforço,Jan,18.0,Q1,1.0,1.011819e+09,Daily
3687,2026-01-28,Trabalhado,244198,Esforço,Esforço,Jan,19.0,Q1,1.0,8.740469e+08,Daily
3688,2026-01-29,Trabalhado,300762,Esforço,Esforço,Jan,20.0,Q1,1.0,1.159066e+09,Daily
3689,2026-01-30,Trabalhado,312753,Esforço,Esforço,Jan,21.0,Q1,1.0,1.054818e+09,Daily
3690,2026-01-31,Trabalhado,104916,Esforço,Esforço,N/A,0.0,0,0.0,5.558929e+08,Daily

In [ ]:
#df_sms
# df_rcs,
# df_email,
# df_telefones,
# df_blacklist_expert
#df_mailing_hist_processing
mask = df_mailing_hist_processing.duplicated(subset=['DATA', 'CPF'], keep=False)

df_duplicados = df_mailing_hist_processing[mask].sort_values(['DATA', 'CPF'])

df_duplicados

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,VALOR,FX_ATRASO
43421,2026-01-01,0001934136,10223017990,210,253,1,9.98,181-210
43464,2026-01-01,0000036817,10223017990,1214,253,1,2797.73,360 acima
39752,2026-01-01,0001732659,1309716188,1483,253,1,255.12,360 acima
39757,2026-01-01,0001595851,1309716188,936,253,1,415.11,360 acima
41140,2026-01-01,0001201654,1549845586,1498,253,1,39.14,360 acima
...,...,...,...,...,...,...,...,...
1381433,2026-01-31,0000027840,93386575153,580,253,1,4.67,360 acima
1382308,2026-01-31,0001068843,94024278568,747,253,1,409.75,360 acima
1382309,2026-01-31,0000909157,94024278568,788,253,1,2316.83,360 acima
1387150,2026-01-31,0001256390,99150549200,1528,253,1,1426.91,360 acima
1387201,2026-01-31,0001115858,99150549200,98,253,1,48.32,091-120

In [ ]:
from utils.digital_channels.data_processing import data_channels, unpack_results
from Ouze.src.config import OUZE_PATHS

# Exemplo de uso
df_channels_processing = data_channels(
    df_mailing_hist=df_mailing_hist_processing,
    df_dw_calendario=df_dw_calendario,
    df_sms=df_sms,
    df_email=df_email,
    df_rcs=df_rcs,
    output_path=OUZE_PATHS["digital"],  # Path passado aqui!
)

INFO:utils.utils:
============================================================
INFO:utils.utils:Salvando DataFrames do canal: SMS
INFO:utils.utils:Destino: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_sms
INFO:utils.utils:============================================================
INFO:utils.utils:Diretório verificado/criado: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_sms
INFO:utils.utils:✓ Salvo: sms_enr_20260212.csv (11386 linhas)
INFO:utils.utils:✓ Salvo: sms_sf_20260212.csv (914 linhas)
INFO:utils.utils:
============================================================
INFO:utils.utils:Resumo do salvamento em: data_sms
INFO:utils.utils:  ✓ Sucessos: 2/2
INFO:utils.utils:============================================================
INFO:utils.utils:
============================================================
INFO:utils.utils:Salvando DataFrames do canal: EMAIL
INFO:utils.utils:Destino: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_email
INFO:utils.utils:============================================================
INFO:utils.utils:Diretório verificado/criado: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_email
INFO:utils.utils:✓ Salvo: email_enr_20260212.csv (63317 linhas)
INFO:utils.utils:✓ Salvo: email_sf_20260212.csv (3246 linhas)
INFO:utils.utils:
============================================================
INFO:utils.utils:Resumo do salvamento em: data_email
INFO:utils.utils:  ✓ Sucessos: 2/2
INFO:utils.utils:============================================================
INFO:utils.utils:
============================================================
INFO:utils.utils:Salvando DataFrames do canal: RCS
INFO:utils.utils:Destino: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_rcs
INFO:utils.utils:============================================================
INFO:utils.utils:Diretório verificado/criado: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\Data\data_analytcs\analytical_digital\data_rcs
INFO:utils.utils:✓ Salvo: rcs_enr_20260212.csv (11386 linhas)
INFO:utils.utils:✓ Salvo: rcs_sf_20260212.csv (914 linhas)
INFO:utils.utils:
============================================================
INFO:utils.utils:Resumo do salvamento em: data_rcs
INFO:utils.utils:  ✓ Sucessos: 2/2
INFO:utils.utils:============================================================
INFO:utils.utils:
============================================================
INFO:utils.utils:RESUMO GERAL - DIGITAL
INFO:utils.utils:  Canais processados: 3
INFO:utils.utils:  Arquivos salvos: 6/6
INFO:utils.utils:============================================================

{'sms': (            DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  0     2026-01-15   5027943997   211-240    253.0         10.0      Q1     1.0
  1     2026-01-15  93216009904   241-270    253.0         10.0      Q1     1.0
  2     2026-01-15  10588183172   331-360    253.0         10.0      Q1     1.0
  3     2026-01-15  88158632149   301-330    253.0         10.0      Q1     1.0
  4     2026-01-15   6169325291   241-270    253.0         10.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  12295 2026-01-28  47773375291   181-210    253.0         19.0      Q1     1.0
  12296 2026-01-28  56748264120   331-360    253.0         19.0      Q1     1.0
  12297 2026-01-28   5738129180   181-210    253.0         19.0      Q1     1.0
  12298 2026-01-28  41025326253   241-270    253.0         19.0      Q1     1.0
  12299 2026-01-28    968179924   181-210    253.0         19.0      Q1     1.0

        mes_abreviado
  0               Jan
  1               Jan
  2               Jan
  3               Jan
  4               Jan
  ...             ...
  12295           Jan
  12296           Jan
  12297           Jan
  12298           Jan
  12299           Jan

  [11386 rows x 8 columns],
              DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  544   2026-01-15   6223954913       NaN      NaN         10.0      Q1     1.0
  2391  2026-01-21   7038261401       NaN      NaN         14.0      Q1     1.0
  2398  2026-01-21   4052422201       NaN      NaN         14.0      Q1     1.0
  2403  2026-01-21   2400739919       NaN      NaN         14.0      Q1     1.0
  2407  2026-01-21    917772326       NaN      NaN         14.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  12239 2026-01-14   3338714130       NaN      NaN          9.0      Q1     1.0
  12241 2026-01-14  15964362800       NaN      NaN          9.0      Q1     1.0
  12258 2026-01-14  62791982272       NaN      NaN          9.0      Q1     1.0
  12273 2026-01-14   1427327106       NaN      NaN          9.0      Q1     1.0
  12286 2026-01-14  98792806287       NaN      NaN          9.0      Q1     1.0

        mes_abreviado
  544             Jan
  2391            Jan
  2398            Jan
  2403            Jan
  2407            Jan
  ...             ...
  12239           Jan
  12241           Jan
  12258           Jan
  12273           Jan
  12286           Jan

  [914 rows x 8 columns]),
 'email': (            DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  0     2026-01-05   1437114156   211-240    253.0            2      Q1       1
  1     2026-01-05  72327561272   331-360    253.0            2      Q1       1
  2     2026-01-05  72327561272   331-360    253.0            2      Q1       1
  3     2026-01-05  70323704115   211-240    253.0            2      Q1       1
  4     2026-01-05  99037653120   241-270    253.0            2      Q1       1
  ...          ...          ...       ...      ...          ...     ...     ...
  66558 2026-01-29  71736956272   091-120    253.0           20      Q1       1
  66559 2026-01-29  71736956272   091-120    253.0           20      Q1       1
  66560 2026-01-29  71736956272   091-120    253.0           20      Q1       1
  66561 2026-01-29   5109788359   151-180    253.0           20      Q1       1
  66562 2026-01-29  66795427234   091-120    253.0           20      Q1       1

        mes_abreviado
  0               Jan
  1               Jan
  2               Jan
  3               Jan
  4               Jan
  ...             ...
  66558           Jan
  66559           Jan
  66560           Jan
  66561           Jan
  66562           Jan

  [63317 rows x 8 columns],
              DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  872   2026-01-05  43538738220       NaN      NaN            2      Q1       1
  873   2026-01-05  43538738220       NaN      NaN            2      Q1       1
  874   2026-01-05  43538738220       NaN      NaN            2      Q1       1
  1092  2026-01-05  58814205272       NaN      NaN            2      Q1       1
  1093  2026-01-05  58814205272       NaN      NaN            2      Q1       1
  ...          ...          ...       ...      ...          ...     ...     ...
  65659 2026-01-21    500603251       NaN      NaN           14      Q1       1
  65740 2026-01-21    445453044       NaN      NaN           14      Q1       1
  65741 2026-01-21    445453044       NaN      NaN           14      Q1       1
  65742 2026-01-21    445453044       NaN      NaN           14      Q1       1
  66526 2026-01-29  27422305215       NaN      NaN           20      Q1       1

        mes_abreviado
  872             Jan
  873             Jan
  874             Jan
  1092            Jan
  1093            Jan
  ...             ...
  65659           Jan
  65740           Jan
  65741           Jan
  65742           Jan
  66526           Jan

  [3246 rows x 8 columns]),
 'rcs': (            DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  0     2026-01-05  78541590925   091-120    253.0          2.0      Q1     1.0
  1     2026-01-05  43881963987   151-180    253.0          2.0      Q1     1.0
  2     2026-01-05  72742348115   091-120    253.0          2.0      Q1     1.0
  3     2026-01-05   1525997971   151-180    253.0          2.0      Q1     1.0
  5     2026-01-05    241485126   091-120    253.0          2.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  12295 2026-01-28  47773375291   181-210    253.0         19.0      Q1     1.0
  12296 2026-01-28  56748264120   331-360    253.0         19.0      Q1     1.0
  12297 2026-01-28   5738129180   181-210    253.0         19.0      Q1     1.0
  12298 2026-01-28  41025326253   241-270    253.0         19.0      Q1     1.0
  12299 2026-01-28    968179924   181-210    253.0         19.0      Q1     1.0

        mes_abreviado
  0               Jan
  1               Jan
  2               Jan
  3               Jan
  5               Jan
  ...             ...
  12295           Jan
  12296           Jan
  12297           Jan
  12298           Jan
  12299           Jan

  [11386 rows x 8 columns],
              DATA          CPF FX_ATRASO  COD_CLI  nr_dia_util quartil  dt_mes  \
  4     2026-01-05   1675714940       NaN      NaN          2.0      Q1     1.0
  14    2026-01-05  42151937100       NaN      NaN          2.0      Q1     1.0
  48    2026-01-05  15115704072       NaN      NaN          2.0      Q1     1.0
  73    2026-01-05  54847001591       NaN      NaN          2.0      Q1     1.0
  104   2026-01-05  28518462215       NaN      NaN          2.0      Q1     1.0
  ...          ...          ...       ...      ...          ...     ...     ...
  10955 2026-01-22  45743525900       NaN      NaN         15.0      Q1     1.0
  11900 2026-01-28  38466198172       NaN      NaN         19.0      Q1     1.0
  11904 2026-01-28  25036521315       NaN      NaN         19.0      Q1     1.0
  11936 2026-01-28   4573681280       NaN      NaN         19.0      Q1     1.0
  12004 2026-01-28   3486385232       NaN      NaN         19.0      Q1     1.0

        mes_abreviado
  4               Jan
  14              Jan
  48              Jan
  73              Jan
  104             Jan
  ...             ...
  10955           Jan
  11900           Jan
  11904           Jan
  11936           Jan
  12004           Jan

  [914 rows x 8 columns]),
 'saved_files': {'sms': {'sms_enr': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_sms\\sms_enr_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 11386},
   'sms_sf': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_sms\\sms_sf_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 914}},
  'email': {'email_enr': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_email\\email_enr_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 63317},
   'email_sf': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_email\\email_sf_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 3246}},
  'rcs': {'rcs_enr': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_rcs\\rcs_enr_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 11386},
   'rcs_sf': {'status': 'success',
    'caminho': 'C:\\Users\\claudiano.alves\\Documents\\Claudiano\\repository\\Data-Analysis-Portfolio\\Projects\\Ouze\\Data\\data_analytcs\\analytical_digital\\data_rcs\\rcs_sf_20260212.csv',
    'mensagem': 'Arquivo salvo com sucesso',
    'linhas': 914}}}}

In [85]:
from utils.digital_channels.data_processing import data_channels, unpack_results
(
    sms_enr, sms_sf, 
    email_enr, email_sf, 
    rcs_enr, rcs_sf
) = unpack_results(df_channels_processing)
email_enr

,DATA,CPF,FX_ATRASO,COD_CLI,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,1437114156,211-240,253.0,2,Q1,1,Jan
1,2026-01-05,72327561272,331-360,253.0,2,Q1,1,Jan
2,2026-01-05,72327561272,331-360,253.0,2,Q1,1,Jan
3,2026-01-05,70323704115,211-240,253.0,2,Q1,1,Jan
4,2026-01-05,99037653120,241-270,253.0,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...
66558,2026-01-29,71736956272,091-120,253.0,20,Q1,1,Jan
66559,2026-01-29,71736956272,091-120,253.0,20,Q1,1,Jan
66560,2026-01-29,71736956272,091-120,253.0,20,Q1,1,Jan
66561,2026-01-29,5109788359,151-180,253.0,20,Q1,1,Jan
66562,2026-01-29,66795427234,091-120,253.0,20,Q1,1,Jan

In [94]:
from utils.digital_channels.metricas_acumuladas import acumulado_unique, acumulado_por_faixa_atraso, acumulado_esforco

df_acumulado_canais_digitais = acumulado_por_faixa_atraso(
    df_dw_calendario=df_dw_calendario,
    df_sms=sms_enr,
    df_email=email_enr,
    df_rcs=rcs_enr
)
df_acumulado_canais_digitais

,DATA,CANAL,FX_ATRASO,QTD_CPF,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,SMS,Preventivo,0,2,Q1,1,Jan
1,2026-01-05,SMS,000-030,0,2,Q1,1,Jan
2,2026-01-05,SMS,031-060,0,2,Q1,1,Jan
3,2026-01-05,SMS,061-090,0,2,Q1,1,Jan
4,2026-01-05,SMS,091-120,156,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...
765,2026-01-28,RCS,241-270,280,19,Q1,1,Jan
766,2026-01-28,RCS,271-300,173,19,Q1,1,Jan
767,2026-01-28,RCS,301-330,125,19,Q1,1,Jan
768,2026-01-28,RCS,331-360,139,19,Q1,1,Jan
769,2026-01-28,RCS,360 acima,1804,19,Q1,1,Jan